/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this configuration to define settings for access to Google services.
 */
export interface AccountGoogle {
  /**
   * The name that apps show to the user for this Google account. If not present, the system generates a suitable default.
   */
  VisibleName?: string;
  /**
   * The identifier of an asset declaration that contains the user identity for this Google account. Set the corresponding asset type to 'UserIdentity' and ensure that it contains an 'EmailAddress' key that specifies the full Google email address for the account.
   */
  UserIdentityAssetReference: string;
}
