/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Retrieves the Activation Lock bypass code from the device.
 */
export interface ActivationLockBypassCodeCommand {
  PayloadKeys?: {};
  ResponseKeys?: {
    /**
     * The Activation Lock bypass code if it's available.
     */
    ActivationLockBypassCode: string;
  };
}
