/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command queries the device for application feedback information. This command requires the App Management right.
 */
export interface AppFeedbackCommand {
  PayloadKeys?: {
    /**
     * The bundle identifiers of the managed apps.
     */
    Identifiers?: string[];
    /**
     * If 'true', delete the app's feedback dictionary after the server reads it.
     */
    DeleteFeedback?: boolean;
  };
  ResponseKeys?: {
    /**
     * An array of managed app feedback items.
     */
    ManagedApplicationFeedback: {
      /**
       * The app's bundle identifier.
       */
      Identifier: string;
      /**
       * The app's feedback.
       */
      Feedback?: {
        /**
         * The app's feedback items.
         */
        ANY?: string;
      };
    }[];
  };
}
