/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command queries the device for the current configuration of managed applications. This command requires the App Management right. macOS supports this command as of 10.15, on the device channel and for User Enrollments only, because Settings->ApplicationConfiguration is supported. Since macOS does not support Managed Applications, this command can be used for any bundle identifier.
 */
export interface AppConfigurationCommand {
  PayloadKeys?: {
    /**
     * The bundle identifiers of the managed apps.
     */
    Identifiers?: string[];
  };
  ResponseKeys?: {
    /**
     * An array of app configurations items.
     */
    ApplicationConfigurations: {
      /**
       * The app's bundle identifier.
       */
      Identifier: string;
      /**
       * The app's configurations.
       */
      Configuration?: {
        /**
         * The app's configuration items.
         */
        ANY?: string;
      };
    }[];
  };
}
