/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * If a redemption code is needed during app installation, the server can use this command to complete the app installation.
 */
export interface ApplyRedemptionCodeCommand {
  /**
   * The bundle identifier of the app.
   */
  Identifier: string;
  /**
   * The redemption code that applies to the app pending installation.
   */
  RedemptionCode: string;
}
