/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to query for installed 3rd party applications.
 */
export interface ApplicationListCommand {
  PayloadKeys?: {
    /**
     * An array of app identifiers. Provide this value to limit the response to only include these apps. This value is available in iOS 7 and later, macOS 10.15 and later, and tvOS 10.2 and later.
     */
    Identifiers?: string[];
    /**
     * If 'true', only get a list of managed apps. This value is available in iOS 7 and later, macOS 10.15 and later, and tvOS 10.2 and later.
     */
    ManagedAppsOnly?: boolean;
    /**
     * An array of strings representing keys in the InstalledApplicationListItem dictionary. If provided, the response will contain only the keys listed here. The "Identifier" key is always included. If not present, the response will contain all keys. Always request just the set of keys that will actually be used, as some key values can take significant time and power to calculate on the device.
     */
    Items?: (
      | "AdHocCodeSigned"
      | "AppStoreVendable"
      | "BetaApp"
      | "BundleSize"
      | "DeviceBasedVPP"
      | "DynamicSize"
      | "ExternalVersionIdentifier"
      | "HasUpdateAvailable"
      | "Identifier"
      | "Installing"
      | "IsAppClip"
      | "IsValidated"
      | "Name"
      | "ShortVersion"
      | "Version"
    )[];
  };
  ResponseKeys?: {
    /**
     * An array of dictionaries that describes each installed app.
     */
    InstalledApplicationList: {
      /**
       * The app's identifier. This key will always be present on iOS/tvOS but may be missing on macOS.
       */
      Identifier?: string;
      /**
       * The app's external version identifier, which you can use in the iTunes Search API to determine if an updated version of the app is available. Compare this value to the 'externalId' value in the 'contentMetadataLookupUrl' response from the 'VPPServiceConfigSrv' endpoint. If these values don't match, an updated version of the app may be available.
       * A newer version of an app may not be available for installation on the device for a variety of reasons, including that the device's operating system version or hardware is incompatible with the available version of the app.
       */
      ExternalVersionIdentifier?: number;
      /**
       * The app's version.
       */
      Version?: string;
      /**
       * The app's short version.
       */
      ShortVersion?: string;
      /**
       * The app's name.
       */
      Name?: string;
      /**
       * The app's static bundle size, in bytes. This value is available in iOS 5 and later, and macOS 10.7 and later, and tvOS 10.2 and later.
       */
      BundleSize?: number;
      /**
       * The size of the app's file system in bytes, including the Documents, Library, and other directories. This value is available in iOS 5 and later, and tvOS 10.2 and later.
       */
      DynamicSize?: number;
      /**
       * If 'true', the app is valid and can run on the device. If the app is enterprise-distributed and unvalidated, it won't be able to run until validation has occurred. This value is available in iOS 9.2 and later, and tvOS 10.2 and later.
       */
      IsValidated?: boolean;
      /**
       * If 'true', the app is downloading. If 'false', it's already installed.
       */
      Installing?: boolean;
      /**
       * If 'true', the app came from the App Store and can participate in store features. For device-based Volume Purchase Program (VPP) apps, this value is 'false'. This value is available in iOS 11.3 and later, and tvOS 11.3 and later.
       */
      AppStoreVendable?: boolean;
      /**
       * If 'true', installing the app didn't require an Apple ID. This value is available in iOS 11.3 and later, and tvOS 11.3 and later.
       */
      DeviceBasedVPP?: boolean;
      /**
       * If 'true', the app is part of the Apple Beta Software Program. This value is available in iOS 11.3 and later, and tvOS 11.3 and later.
       */
      BetaApp?: boolean;
      /**
       * If 'true', the app is ad-hoc code signed. This query is available in iOS 11.3 and later, and tvOS 11.3 and later.
       */
      AdHocCodeSigned?: boolean;
      /**
       * If 'true', the app has an update available. This key is present only for App Store apps. In macOS, this key is present only for Volume Purchase Program (VPP) apps. This status updates daily and isn't always up-to-date when installing an app.
       */
      HasUpdateAvailable?: boolean;
      /**
       * If 'true', the download failed.
       */
      DownloadFailed?: boolean;
      /**
       * If 'true', the app is in the initial state, which is waiting to download.
       */
      DownloadWaiting?: boolean;
      /**
       * If 'true', the user paused the download.
       */
      DownloadPaused?: boolean;
      /**
       * If 'true', the user canceled the download.
       */
      DownloadCancelled?: boolean;
      /**
       * If 'true', the app is an App Clip. Available in iOS 16 and later.
       */
      IsAppClip?: boolean;
    }[];
  };
}
