/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Returns information about the active NSExtensions for a particular user.
 */
export interface ApplicationListActiveNSExtensions {
  PayloadKeys?: {
    /**
     * An array of extension points. If you choose to provide this value, the response only includes the app extensions for the extension points you specify.
     */
    FilterExtensionPoints?: string[];
  };
  ResponseKeys?: {
    /**
     * An array of dictionaries that contains information about active extensions on the device.
     */
    Extensions: {
      /**
       * The identifier of the extension.
       */
      Identifier: string;
      /**
       * The NSExtensionPointIdentifier for the extension.
       */
      ExtensionPoint: string;
      /**
       * The extension's display name.
       */
      DisplayName: string;
      /**
       * The display name of the container.
       */
      ContainerDisplayName?: string;
      /**
       * The identifier of the container.
       */
      ContainerIdentifier?: string;
      /**
       * The path to the extension.
       */
      Path: string;
      /**
       * The version of the extension.
       */
      Version: string;
      /**
       * The user-selected state of the extension, which a user sets in the Extensions preference pane in System Preferences.
       */
      UserElection: "Default" | "Use" | "Ignore";
    }[];
  };
}
