/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to retrieve the list of installed certificates on the device. The command requires that the server has the Inspect Profile Manifest privilege. For userenrollment, this request will limit to certificates pushed via MDM. Starting with iOS 15.4, the CertificateList command will return a Not Now response prior to the first time a passcode-protected device is unlocked after boot. Between iOS 15.0 and iOS 15.4, devices in that state did not respond with Not Now, but some identity certificates may not have been reported in the response.
 */
export interface CertificateListCommand {
  PayloadKeys?: {
    /**
     * If 'true', only include certificates that MDM installed or that are in the same profile as the MDM payload. User-enrolled devices ignore this value and always only include managed certificates. This value is available in iOS 13 and later, macOS 10.15 and later, and tvOS 13 and later.
     */
    ManagedOnly?: boolean;
  };
  ResponseKeys?: {
    /**
     * An array of certificate list items that describes each certificate.
     */
    CertificateList: {
      /**
       * The certificate's common name.
       */
      CommonName: string;
      /**
       * If 'true', this is an identity certificate.
       */
      IsIdentity: boolean;
      /**
       * The certificate in DER-encoded X.509 format.
       */
      Data: string;
    }[];
  };
}
