/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to clear the passcode on the device. This command requires the Device Lock and Passcode Removal right.
 */
export interface ClearPasscodeCommand {
  /**
   * The unlock token value that the device provides in its 'TokenUpdateMessage' check-in message.
   */
  UnlockToken: string;
}
