/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleFinder {
  /**
   * If 'true', the system disables the Finder's burn support.
   */
  ProhibitBurn?: boolean;
  /**
   * Specifies whether Finder should operate in Simple or Full mode.
   */
  InterfaceLevel?: "Simple" | "Full";
  /**
   * If 'true', the system disables Connect to Server.
   */
  ProhibitConnectTo?: boolean;
  /**
   * If 'true', the system disables Eject.
   */
  ProhibitEject?: boolean;
  /**
   * If 'true', the system disables Go to Folder.
   */
  ProhibitGoToFolder?: boolean;
  /**
   * If 'false', external hard drives don't appear on the Desktop.
   */
  ShowExternalHardDrivesOnDesktop?: boolean;
  /**
   * If 'false', internal hard drives don't appear on the Desktop.
   */
  ShowHardDrivesOnDesktop?: boolean;
  /**
   * If 'false', mounted file servers don't appear on the Desktop.
   */
  ShowMountedServersOnDesktop?: boolean;
  /**
   * If 'false', removable media items don't appear on the Desktop.
   */
  ShowRemovableMediaOnDesktop?: boolean;
  /**
   * If 'false', the user isn't warned before emptying the trash.
   */
  WarnOnEmptyTrash?: boolean;
}
