/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Global HTTP Proxy (Supervised devices only)
 */
export interface ComAppleProxyHttpGlobal {
  /**
   * The proxy type. For a manual proxy type, the profile contains the proxy server address, including its port, and optionally a user name and password. For an auto proxy type, you can enter a PAC URL.
   */
  ProxyType?: "Manual" | "Auto";
  /**
   * The proxy server's network address. This is required if the ProxyType is set to Manual, and is ignored if the ProxyType is set to Automatic.
   */
  ProxyServer?: string;
  /**
   * The proxy server's port number. This is required if the ProxyType is set to Manual, and is ignored if the ProxyType is set to Automatic.
   */
  ProxyServerPort?: number;
  /**
   * The user name used to authenticate to the proxy server. This setting is only used if the ProxyType is set to Manual, and is ignored if the ProxyType is set to Automatic.
   */
  ProxyUsername?: string;
  /**
   * The password used to authenticate to the proxy server. This setting is only used if the ProxyType is set to Manual, and is ignored if the ProxyType is set to Automatic.
   */
  ProxyPassword?: string;
  /**
   * The URL of the PAC file that defines the proxy configuration. Starting in iOS 13 and macOS 10.15, only URLs that begin with 'http://' or 'https://' are allowed. This setting is only used if the ProxyType is set to Automatic, and is ignored if the ProxyType is set to Manual.
   */
  ProxyPACURL?: string;
  /**
   * If 'true', allows connecting directly to the destination if the proxy autoconfiguration (PAC) file is unreachable.
   */
  ProxyPACFallbackAllowed?: boolean;
  /**
   * If 'true', allows the device to bypass the proxy server to display the login page for captive networks.
   */
  ProxyCaptiveLoginAllowed?: boolean;
}
