/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define custom APNs for cellular data access.
 */
export interface ComAppleCellular {
  /**
   * A configuration dictionary.
   */
  AttachAPN?: {
    /**
     * The name for this configuration.
     */
    Name: string;
    /**
     * The authentication type.
     */
    AuthenticationType?: "CHAP" | "PAP";
    /**
     * The user name for the APN.
     */
    Username?: string;
    /**
     * The password for the APN.
     */
    Password?: string;
    /**
     * The supported Internet Protocol versions. Possible values are:
     * 1 = IPv4
     * 2 = IPv6
     * 3 = Both
     */
    AllowedProtocolMask?: 1 | 2 | 3;
  };
  /**
   * An array of access point dictionaries.
   */
  APNs?: {
    /**
     * The name for this configuration.
     */
    Name: string;
    /**
     * The authentication type for logging in.
     */
    AuthenticationType?: "CHAP" | "PAP";
    /**
     * The user name for the APN.
     */
    Username?: string;
    /**
     * The user's password for the APN.
     */
    Password?: string;
    /**
     * The proxy server's address.
     */
    ProxyServer?: string;
    /**
     * The proxy server's port number.
     */
    ProxyPort?: number;
    /**
     * Deprecated. The default Internet Protocol versions. Possible values are:
     * * '1': IPv4
     * * '2': IPv6
     * * '3': Both
     * Available in iOS 10.3 but no longer used in iOS 11 and later.
     */
    DefaultProtocolMask?: 1 | 2 | 3;
    /**
     * The supported Internet Protocol versions. Possible values are:
     * * '1': IPv4
     * * '2': IPv6
     * * '3': Both
     * Available in iOS 10.3 and later.
     */
    AllowedProtocolMask?: 1 | 2 | 3;
    /**
     * The supported Internet Protocol versions while roaming. Possible values are:
     * * '1': IPv4
     * * '2': IPv6
     * * '3': Both
     * Available in iOS 10.3 and later.
     */
    AllowedProtocolMaskInRoaming?: 1 | 2 | 3;
    /**
     * The supported Internet Protocol versions while roaming domestically. Possible values are:
     * * '1': IPv4
     * * '2': IPv6
     * * '3': Both
     * Available in iOS 10.3 and later.
     */
    AllowedProtocolMaskInDomesticRoaming?: 1 | 2 | 3;
    /**
     * If 'true', enables XLAT464. Available in iOS 16 and later and watchOS 9 and later.
     */
    EnableXLAT464?: boolean;
  }[];
}
