/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleVpnManagedApplayer {
  /**
   * A globally unique identifier for this VPN configuration.
   */
  VPNUUID: string;
  /**
   * An array with entries that must each specify a domain that triggers the VPN connection in Safari. Each entry is in the format 'www.apple.com'.
   */
  SafariDomains?: string[];
  /**
   * An array with entries that must each specify a domain that triggers this VPN connection in Mail. Each entry is in the format 'www.apple.com'.
   * This property is deprecated in iOS 13.4 and later; use the 'VPNUUID' property of the Mail or ExchangeActiveSync payload instead.
   */
  MailDomains?: string[];
  /**
   * An array with entries that must each specify a domain that triggers this VPN connection in Calendar. Each entry is in the format 'www.apple.com'.
   * This property is deprecated in iOS 13.4 and later; use the 'VPNUUID' property of the CalDAV payload instead.
   */
  CalendarDomains?: string[];
  /**
   * An array with entries that must each specify a domain that triggers this VPN connection in Contacts. Each entry is in the format 'www.apple.com'.
   * This property is deprecated in iOS 13.4 and later; use the 'VPNUUID' property of the CardDAV payload instead.
   */
  ContactsDomains?: string[];
  /**
   * An array with entries that must each specify a domain that triggers this VPN. The domains must also be part of the 'apple-app-site-association' file, as described in Supporting associated domains.
   * Available in iOS 14 and later, and macOS 11 and later.
   */
  AssociatedDomains?: string[];
  /**
   * An array with entries that each specify a domain that doesn't trigger this VPN for connections to the domain.
   * Available in iOS 14 and later, and macOS 11 and later.
   */
  ExcludedDomains?: string[];
  /**
   * If 'true', automatically connects the VPN when associated apps for this per-app VPN service initiate network communication. Otherwise, the user must initiate the connection manually before those apps can initiate network communication. If this key isn't present, the value of the 'OnDemandEnabled' key determines the status of per-app VPN On Demand.
   */
  OnDemandMatchAppEnabled?: boolean;
  /**
   * An array of SMB domains that's accessible through this VPN connection.
   * Available in iOS 13 and later.
   */
  SMBDomains?: string[];
}
