/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for configuration access to AIM servers.
 */
export interface ComAppleAIMAccount {
  /**
   * The description of the account.
   */
  AIMAccountDescription?: string;
  /**
   * The server address.
   */
  AIMHostName: "slogin.oscar.aol.com";
  /**
   * The user's login name.
   */
  AIMUserName?: string;
  /**
   * The user's password.
   */
  AIMPassword?: string;
  /**
   * If 'true', enables SSL.
   */
  AIMUseSSL?: boolean;
  /**
   * The connection port for the server.
   */
  AIMPort?: number;
  /**
   * The authentication method for the account.
   */
  AIMAuthentication: "AIMAuthPassword";
}
