/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for configuration access to Jabber servers.
 */
export interface ComAppleJabberAccount {
  /**
   * The description of the account.
   */
  JabberAccountDescription?: string;
  /**
   * The server's address.
   */
  JabberHostName: string;
  /**
   * The user's user name.
   */
  JabberUserName?: string;
  /**
   * The user's password.
   */
  JabberPassword?: string;
  /**
   * If 'true', enables SSL.
   */
  JabberUseSSL?: boolean;
  /**
   * The server's port.
   */
  JabberPort?: number;
  /**
   * The authentication method for the account.
   */
  JabberAuthentication: "JabberAuthPassword";
}
