/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define a macOS Server account
 */
export interface ComAppleOsxserverAccount {
  /**
   * The server's address.
   */
  HostName: string;
  /**
   * The user's user name.
   */
  UserName: string;
  /**
   * The user's password.
   */
  Password?: string;
  /**
   * The description of the account.
   */
  AccountDescription?: string;
  /**
   * Array of dictionaries containing configured account types and relevant settings
   */
  ConfiguredAccounts: {
    /**
     * com.apple.osxserver.documents (the Documents account type).
     */
    Type: "com.apple.osxserver.documents";
    /**
     * Designates the port number to use when contacting the server. If no port number is specified, the default port is used.
     */
    Port?: number;
  }[];
}
