/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for Associated Domains to be used with features such as Extensible AppSSO, universal links and Password AutoFill.
 */
export interface ComAppleAssociatedDomains {
  /**
   * A dictionary that maps apps to their associated domains.
   */
  Configuration: {
    /**
     * The app identifier to associate the domains with.
     */
    ApplicationIdentifier: string;
    /**
     * The domains to be associated with the app. Each string is in the form of ''service:domain''. Domains should be fully qualified hostnames, like 'www.example.com'.
     * See Supporting associated domains for more information.
     */
    AssociatedDomains: string[];
    /**
     * If 'true', data for this domain should be downloaded directly instead of through a CDN. The entitlement value for this domain must be set to 'service:domain?mode=managed' or this value will be ignored. Available in macOS 11 and later.
     */
    EnableDirectDownloads?: boolean;
  }[];
}
