/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Active Directory Certificate
 */
export interface ComAppleADCertificateManaged {
  /**
   * The fully qualified host name of the CA.
   */
  CertServer: string;
  /**
   * The certificate template for your environment. The default user certificate value is `User`. The default computer certificate value is `Machine`.
   */
  CertTemplate: string;
  /**
   * A user-friendly description of the certification identity.
   */
  Description?: string;
  /**
   * The number of days in advance of certificate expiration that the notification center notifies the user.
   */
  CertificateRenewalTimeInterval?: number;
  /**
   * The name of the certificate authority (CA). This value is determined from the common name (CN) of the Active Directory entry. Available in macOS 10.8 and later.
   *
   * Valid values:
   * * CN=<your CA Name>
   * * CN='Certification Authorities'
   * * CN='Public Key Services'
   * * ''CN='Services'
   * * ''CN='Configuration'
   * * ''CN=<your base Domain Name>
   */
  CertificateAuthority?: string;
  /**
   * This value is most commonly 'RPC'; if using web enrollment, use 'HTTP'. Available in macOS 10.8 and later.
   */
  CertificateAcquisitionMechanism?: string;
  /**
   * If 'true', gives apps access to the private key. Available in macOS 10.10 and later.
   */
  AllowAllAppsAccess?: boolean;
  /**
   * If 'true', the user is prompted for credentials when the profile is installed. This key applies only to user certificates with the Manual Download profile delivery method. Omit this key for computer certificates. Available in macOS 10.8 and later.
   */
  PromptForCredentials?: boolean;
  /**
   * If 'true', allows exporting the private key. Available in macOS 10.10 and later.
   */
  KeyIsExtractable?: boolean;
  /**
   * The RSA key size for the certificate signing request (CSR). Available in macOS 10.11 and later.
   */
  Keysize?: number;
  /**
   * If 'true', the certificate obtained with this payload attempts auto-renewal. Auto-renewal can only be used with device Active Directory certificate payloads. Available in macOS 10.13.4 and later.
   */
  EnableAutoRenewal?: boolean;
}
