/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for profile removal
 */
export interface ComAppleProfileRemovalPassword {
  /**
   * The password for allowing the profile to be removed.
   */
  RemovalPassword?: string;
}
