/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for a pem certificate.
 */
export interface ComAppleSecurityPem {
  /**
   * The file name of the enclosed certificate.
   */
  PayloadCertificateFileName?: string;
  /**
   * The binary representation of the payload, encoded in Base64.
   */
  PayloadContent: string;
}
