/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleMcxloginscripts {
  /**
   * An array of one or more dictionaries of scripts to run at user login time.
   */
  loginscripts?: {
    /**
     * The filename for display purposes.
     */
    filename: string;
    /**
     * The UTF-8 encoded data object representing the executable script.
     */
    filedata: string;
  }[];
  /**
   * An array of one or more dictionaries of scripts to run at user logout time.
   */
  logoutscripts?: {
    /**
     * The filename for display purposes.
     */
    filename: string;
    /**
     * The UTF-8 encoded data object representing the executable script.
     */
    filedata: string;
  }[];
  /**
   * If 'true', doesn't execute the login scripts during login.
   */
  skipLoginHook?: boolean;
  /**
   * If 'true', doesn't execute the logout scripts during logout.
   */
  skipLogoutHook?: boolean;
}
