/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Configures Security Preferences:Privacy settings
 */
export interface ComAppleTCCConfigurationProfilePolicy {
  /**
   * A dictionary whose keys are limited to the privacy policy control services.  In the case of conflicting specifications, the most restrictive setting (deny) is used.
   */
  Services: {
    /**
     * Specifies the policies for contact information managed by the Contacts.app.
     */
    AddressBook?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Specifies the policies for calendar information managed by the Calendar.app.
     */
    Calendar?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Specifies the policies for reminders information managed by the Reminders app.
     */
    Reminders?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * The pictures managed by the Photos app in '~/Pictures/.photoslibrary'.
     */
    Photos?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * A system camera. Access to the camera can't be given in a profile; it can only be denied.
     */
    Camera?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * A system microphone. Access to the microphone can't be given in a profile; it can only be denied.
     */
    Microphone?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Specifies the policies for the app via the Accessibility subsystem.
     */
    Accessibility?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Specifies the policies for the application to use CoreGraphics APIs to send CGEvents to the system event stream.
     */
    PostEvent?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application access to all protected files, including system administration files.
     */
    SystemPolicyAllFiles?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application access to some files used in system administration.
     */
    SystemPolicySysAdminFiles?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Specifies the policies for the app sending restricted AppleEvents to another process.
     */
    AppleEvents?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to access Apple Music, music and video activity, and the media library.
     */
    MediaLibrary?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows a File Provider application to know when the user is using files managed by the File Provider.
     */
    FileProviderPresence?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to use CoreGraphics and HID APIs to listen to (receive) CGEvents and HID events from all processes. Access to these events can't be given in a profile; it can only be denied.
     */
    ListenEvent?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to capture (read) the contents of the system display. Access to the contents can't be given in a profile; it can only be denied.
     */
    ScreenCapture?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to use the system Speech Recognition facility and to send speech data to Apple.
     */
    SpeechRecognition?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to access files in the user's Desktop folder.
     */
    SystemPolicyDesktopFolder?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to access files in the user's Documents folder.
     */
    SystemPolicyDocumentsFolder?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to access files in the user's Downloads folder.
     */
    SystemPolicyDownloadsFolder?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to access files on network volumes.
     */
    SystemPolicyNetworkVolumes?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to access files on removable volumes.
     */
    SystemPolicyRemovableVolumes?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to update or delete other apps. Available in macOS 13 and later.
     */
    SystemPolicyAppBundles?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
    /**
     * Allows the application to access data of other apps.
     */
    SystemPolicyAppData?: {
      /**
       * The bundle ID or installation path of the binary.
       */
      Identifier: string;
      /**
       * The type of identifier value. Application bundles must be identified by bundle ID. Nonbundled binaries must be identified by installation path. Helper tools embedded within an application bundle automatically inherit the permissions of their enclosing app bundle.
       */
      IdentifierType: "bundleID" | "path";
      /**
       * Obtained via the command ''codesign -display -r -''.
       */
      CodeRequirement: string;
      /**
       * If 'true', statically validate the code requirement. Used only if the process invalidates its dynamic code signature.
       */
      StaticCode?: boolean;
      /**
       * If 'true', access is granted; otherwise, the process doesn't have access. The user isn't prompted and can't change this value.
       */
      Allowed: boolean;
      /**
       * The 'Authorization' key is an optional replacement for the 'Allowed' key. Every payload must specify either 'Authorization' or 'Allowed', but not both.
       * 'Allow': Equivalent to a 'true' value for the 'Allowed' key.
       * 'Deny': Equivalent to a 'false' value for the 'Allowed' key.
       * 'AllowStandardUserToSetSystemService:' allows a standard (non-admin) user to configure the permissions for the specified app in the Privacy preferences for services that otherwise require admin authorization. 'AllowStandardUserToSetSystemService' is only valid for the 'ListenEvent' and 'ScreenCapture' services.
       * Available in macOS 11 and later.
       */
      Authorization?: "Allow" | "Deny" | "AllowStandardUserToSetSystemService";
      /**
       * Not used.
       */
      Comment?: string;
      /**
       * The identifier of the process receiving an AppleEvent sent by the Identifier process. This identifier is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifier?: string;
      /**
       * The type of AEReceiverIdentifier value, either 'bundleID' or 'path'. This setting is required for AppleEvents service; not valid for other services.
       */
      AEReceiverIdentifierType?: "bundleID" | "path";
      /**
       * The code requirement for the receiving binary. This code requirement is required for AppleEvents service; not valid for other services.
       */
      AEReceiverCodeRequirement?: string;
    }[];
  };
}
