/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleGlobalethernetManaged {
  /**
   * Keys relevant to 802.1X configuration.   User enrollment payloads do not support the various proxy keys including ProxyType, ProxyServer, ProxyServerPort, ProxyUsername, ProxyPassword, ProxyPACURL and ProxyPACFallbackAllowed.
   */
  ANY?: string;
}
