/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Cellular Private Network Settings and Device Configuration
 */
export interface ComAppleCellularprivatenetworkManaged {
  /**
   * A list of up to 1000 geofences for private networks. Geofencing is only used on iPhone.
   */
  Geofences?: {
    /**
     * The longitude of the geofence.
     */
    Longitude: number;
    /**
     * The latitude of the geofence.
     */
    Latitude: number;
    /**
     * Specifies the radius of the geofence in meters. Set this value slightly greater than the private cellular network coverage area.
     */
    Radius: number;
    /**
     * A geofence identifier that's unique within a list of geofences.
     */
    GeofenceId: string;
  }[];
  /**
   * The name of the private network configuration data set.
   */
  DataSetName: string;
  /**
   * The version number of this dataset that the system uses to track updates.
   */
  VersionNumber: string;
  /**
   * Set to 'true' to prefer this private network over Wi-Fi.
   */
  CellularDataPreferred?: boolean;
  /**
   * Set to 'true' if this private network is NR Standalone.
   */
  EnableNRStandalone?: boolean;
}
