/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleMcxMenuExtras {
  /**
   * The number of seconds to delay after login before adding or removing menu extras. If the delay is too short, the menu extras don't appear, or disappear from the menu bar.
   */
  delaySeconds?: number;
  /**
   * The maximum wait, in seconds, for all menu extras to be added or removed.
   */
  maxWaitSeconds?: number;
  /**
   * If 'true', enables the AirPort menu extra.
   */
  "AirPort.menu"?: boolean;
  /**
   * If 'true', enables the Battery menu extra.
   */
  "Battery.menu"?: boolean;
  /**
   * If 'true', enables the Bluetooth menu extra.
   */
  "Bluetooth.menu"?: boolean;
  /**
   * If 'true', enables the CPU menu extra.
   */
  "CPU.menu"?: boolean;
  /**
   * If 'true', enables the Clock menu extra.
   */
  "Clock.menu"?: boolean;
  /**
   * If 'true', enables the Displays menu extra.
   */
  "Displays.menu"?: boolean;
  /**
   * If 'true', enables the Eject menu extra.
   */
  "Eject.menu"?: boolean;
  /**
   * If 'true', enables the Fax menu extra.
   */
  "Fax.menu"?: boolean;
  /**
   * If 'true', enables the HomeSync menu extra.
   */
  "HomeSync.menu"?: boolean;
  /**
   * If 'true', enables the iChat menu extra.
   */
  "iChat.menu"?: boolean;
  /**
   * If 'true', enables the Ink menu extra.
   */
  "Ink.menu"?: boolean;
  /**
   * If 'true', enables the IrDA menu extra.
   */
  "IrDA.menu"?: boolean;
  /**
   * If 'true', enables the PCCard menu extra.
   */
  "PCCard.menu"?: boolean;
  /**
   * If 'true', enables the PPP menu extra.
   */
  "PPP.menu"?: boolean;
  /**
   * If 'true', enables the PPPoE menu extra.
   */
  "PPPoE.menu"?: boolean;
  /**
   * If 'true', enables the Remote Desktop menu extra.
   */
  "RemoteDesktop.menu"?: boolean;
  /**
   * If 'true', enables the Script menu extra.
   */
  "Script Menu.menu"?: boolean;
  /**
   * If 'true', enables the Spaces menu extra.
   */
  "Spaces.menu"?: boolean;
  /**
   * If 'true', enables the Sync menu extra.
   */
  "Sync.menu"?: boolean;
  /**
   * If 'true', enables the Text Input menu extra.
   */
  "TextInput.menu"?: boolean;
  /**
   * If 'true', enables the TimeMachine menu extra.
   */
  "TimeMachine.menu"?: boolean;
  /**
   * If 'true', enables the Universal Access menu extra.
   */
  "UniversalAccess.menu"?: boolean;
  /**
   * If 'true', enables the User menu extra.
   */
  "User.menu"?: boolean;
  /**
   * If 'true', enables the VPN menu extra.
   */
  "VPN.menu"?: boolean;
  /**
   * If 'true', enables the Volume menu extra.
   */
  "Volume.menu"?: boolean;
  /**
   * If 'true', enables the WWAN menu extra.
   */
  "WWAN.menu"?: boolean;
}
