/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleVpnManagedAppmapping {
  /**
   * The array of VPN mapping dictionaries.
   */
  AppLayerVPNMapping: {
    /**
     * The bundle identifier of the app using the per-app VPN.
     */
    Identifier: string;
    /**
     * The identifier of the per-app VPN payload, which defines the per-app VPN that the app uses. See the 'VPNUUID' key of the AppLayerVPN payload.
     */
    VPNUUID: string;
    /**
     * The code signature designated requirement of the app using the per-app VPN.
     */
    DesignatedRequirement: string;
    /**
     * The code signature signing identifier of the app using the per-app VPN.
     */
    SigningIdentifier: string;
    /**
     * The file-system path of the executable using the per-app VPN.
     */
    Path?: string;
    /**
     * An array of dictionaries. Each dictionary specifies a per-app VPN rule. Use this property to restrict this per-app VPN rule to only match the app's spawned helper tool network traffic.
     * For example, to match network traffic that the 'curl' command generates when run from the Terminal.app, create an app mapping payload for Terminal.app and set the payload's 'MatchTools' key to an array that contains a dictionary that matches the 'curl' command-line tool.
     * If you don't specify the 'MatchTools' key, this per-app VPN rule matches all network traffic that the matching app and its spawned helper tools generate.
     */
    MatchTools?: {
      /**
       * The code signature designated requirement of the command-line tool using the per-app VPN.
       */
      DesignatedRequirement: string;
      /**
       * The code signature signing identifier of the command-line tool using the per-app VPN.
       */
      SigningIdentifier: string;
      /**
       * The file-system path of the command-line tool using the per-app VPN.
       */
      Path?: string;
    }[];
  }[];
}
