/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleNetworkusagerules {
  /**
   * An array of application rules, that apply to only managed apps.
   */
  ApplicationRules?: {
    /**
     * A list of managed app identifiers, as strings, that must follow the associated rules. If this key is missing, the rules apply to all managed apps on the device.
     *
     * Each string in the 'AppIdentifierMatches' array may either be an exact app identifier match (for example, 'com.mycompany.myapp') or it may specify a prefix match for the bundle ID by using the * wildcard character. If used, this character must appear after a period (.) and may only appear once, at the end of the string; for example, 'com.mycompany.*'.
     */
    AppIdentifierMatches?: string[];
    /**
     * If 'false', disables cellular data while roaming for all matching managed apps.
     */
    AllowRoamingCellularData?: boolean;
    /**
     * If 'false', disables cellular data for all matching managed apps.
     */
    AllowCellularData?: boolean;
  }[];
  /**
   * An array of SIM rules, that apply to all apps.
   */
  SIMRules?: {
    /**
     * One or more ICCIDs of SIM cards for which the 'WiFiAssistPolicy' applies. All ICCIDs in all installed Network Usage Rules payloads must be unique. An example ICCID is '89310410106543789301'.
     */
    ICCIDs: string[];
    /**
     * The Wi-Fi Assist policy to apply to the SIM cards specified in the ICCIDs. See About Wi-Fi Assist <https://support.apple.com/en-us/HT205296> to learn more.
     * * '2': Use the default system policy for the specified SIM card(s).
     * * '3': Make Wi-Fi Assist switch more aggressively from a poor Wi-Fi connection to cellular data for the specified SIM card(s). This setting may increase cellular data use and may impact battery life.
     */
    WiFiAssistPolicy: 2 | 3;
  }[];
}
