/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComApplePreferenceSecurity {
  /**
   * If 'true', disables user changes to the password.
   */
  dontAllowPasswordResetUI?: boolean;
  /**
   * If 'true', disables user changes to the lock message.
   */
  dontAllowLockMessageUI?: boolean;
  /**
   * If 'true', disables user changes to the firewall settings.
   */
  dontAllowFireWallUI?: boolean;
}
