/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Parental controls for restricting Siri, Dictation and Profanity
 */
export interface ComAppleIronwoodSupport {
  /**
   * If 'false', suppresses profanity. Use 'forceAssistantProfanityFilter' in Restrictions instead.
   */
  "Profanity Allowed"?: boolean;
  /**
   * If 'false', disables dictation. Use 'allowDictation' in Restrictions instead.
   */
  "Ironwood Allowed"?: boolean;
}
