/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to configure a DNS proxy network extension
 */
export interface ComAppleDnsProxyManaged {
  /**
   * The bundle identifier of the app containing the DNS proxy network extension.
   */
  AppBundleIdentifier: string;
  /**
   * The bundle identifier of the DNS proxy network extension to use. Declaring the bundle identifier is useful for apps that contain more than one DNS proxy extension.
   */
  ProviderBundleIdentifier?: string;
  /**
   * The dictionary of vendor-specific configuration items.
   */
  ProviderConfiguration?: {
    /**
     * Key/value pairs.
     */
    ANY?: string;
  };
  /**
   * A globally-unique identifier for this DNS proxy configuration. Managed apps with the same 'DNSProxyUUID' in their app attributes have their DNS lookups traffic processed by the proxy.
   */
  DNSProxyUUID?: string;
}
