/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleMCX {
  /**
   * If 'true', creates the mobile account at login time.
   */
  "com.apple.cachedaccounts.CreateAtLogin"?: boolean;
  /**
   * If 'true', asks the user if the mobile account should be created and allow the user to not create it.
   */
  "com.apple.cachedaccounts.WarnOnCreate"?: boolean;
  /**
   * If 'true', allows the user to stop the prompts about mobile account creation every time the user logs in. This key is only valid if 'com.apple.cachedaccounts.WarnOnCreate' is set to 'true'.
   */
  "cachedaccounts.WarnOnCreate.allowNever"?: boolean;
  /**
   * The minimum number of seconds a mobile account can exist before an automatic attempt is made to remove the mobile account.
   * Set to '0' to try to remove it at next login or logout time. Set to '-1' to never try to remove the mobile account.
   */
  "cachedaccounts.expiry.delete.disusedSeconds"?: number;
  /**
   * If 'true', bypasses the secure token authorization dialog. This dialog only appears on APFS volumes.
   */
  "cachedaccounts.askForSecureTokenAuthBypass"?: boolean;
}
