/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleDashboard {
  /**
   * If 'true', enables the widget allow list.
   */
  whiteListEnabled: boolean;
  /**
   * An array of widget item dictionaries that are allowed.
   */
  WhiteList: {
    /**
     * The type of allow list item. Set to 'bundleID' to use a widget's bundle ID as its main ID.
     */
    Type: string;
    /**
     * The bundle ID of a widget.
     */
    ID: string;
  }[];
}
