/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleLoginwindow {
  /**
   * If 'true', shows the name and password dialog; if 'false', displays a list of users.
   */
  SHOWFULLNAME?: boolean;
  /**
   * If 'true', shows only network and system users when showing a user list.
   */
  HideLocalUsers?: boolean;
  /**
   * If 'true', shows network users when showing a user list.
   */
  IncludeNetworkUser?: boolean;
  /**
   * If 'true', hides administrator users when showing a user list.
   */
  HideAdminUsers?: boolean;
  /**
   * If 'true', displays Other... when showing a list of users.
   */
  SHOWOTHERUSERS_MANAGED?: boolean;
  /**
   * If this key is included in the payload, its value is displayed in the login window as additional computer information. Before macOS 10.10, this string could contain only certain information (host name, system version, or IP address). After macOS 10.10, setting this key to any value allows the user to click the time area of the menu bar to toggle through various computer information values.
   */
  AdminHostInfo?: "HostName" | "SystemVersion" | "IPAddress";
  /**
   * The list of user GUIDs or group GUIDs of users that are allowed to log in. An asterisk '*' string specifies all users or groups.
   */
  AllowList?: string[];
  /**
   * The list of user GUIDs or group GUIDs of users that cannot log in. This list takes priority over the list in the 'AllowList' key.
   */
  DenyList?: string[];
  /**
   * If 'true', hides mobile account users in a user list. In some cases, mobile users show up as network users.
   */
  HideMobileAccounts?: boolean;
  /**
   * If 'true', disables the Shut Down button.
   */
  ShutDownDisabled?: boolean;
  /**
   * If 'true', disables the Restart item.
   */
  RestartDisabled?: boolean;
  /**
   * If 'true', disables the Sleep button.
   */
  SleepDisabled?: boolean;
  /**
   * If 'true', disregards the '>console' special user name, which will provide a command line UI.
   */
  DisableConsoleAccess?: boolean;
  /**
   * The text to display in the login window.
   */
  LoginwindowText?: string;
  /**
   * If 'true', disables the Shut Down menu item when the user is logged in.
   */
  ShutDownDisabledWhileLoggedIn?: boolean;
  /**
   * If 'true', disables the Restart menu item when the user is logged in.
   */
  RestartDisabledWhileLoggedIn?: boolean;
  /**
   * If 'true', disables the Power Off menu item when the user is logged in.
   */
  PowerOffDisabledWhileLoggedIn?: boolean;
  /**
   * If 'true', disables the Log Out menu item when the user is logged in. Available in macOS 10.13 and later.
   */
  LogOutDisabledWhileLoggedIn?: boolean;
  /**
   * If 'true', disables the immediate Screen Lock functions. Available in macOS 10.13 and later.
   */
  DisableScreenLockImmediate?: boolean;
  /**
   * If 'true', shows the Input Menu in the login window.
   */
  showInputMenu?: boolean;
  /**
   * If 'true', disables the automatic login option when using FileVault.
   */
  DisableFDEAutoLogin?: boolean;
  /**
   * The user short name to set up auto login.
   */
  AutologinUsername?: string;
  /**
   * An optional user password to set up auto login. If this key doesn't exist but a user name does exist, the system sets up auto login the next time the user logs in to the client.
   */
  AutologinPassword?: string;
}
