/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Declarations
 */
export interface ComAppleDeclarations {
  /**
   * The set of declarations to apply. The items in this array are Base64-encoded data representations of the declaration JSON data.
   */
  Declarations: string[];
}
