/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for configuration access to LDAP servers.
 */
export interface ComAppleLdapAccount {
  /**
   * The description of the account.
   */
  LDAPAccountDescription?: string;
  /**
   * The server's address.
   */
  LDAPAccountHostName: string;
  /**
   * The user's user name.
   */
  LDAPAccountUserName?: string;
  /**
   * The user's password. The password is enabled only with encrypted profiles.
   */
  LDAPAccountPassword?: string;
  /**
   * If 'true', enables SSL.
   */
  LDAPAccountUseSSL?: boolean;
  /**
   * An array of search settings dictionaries.
   */
  LDAPSearchSettings?: {
    /**
     * The description of this search setting.
     */
    LDAPSearchSettingDescription?: string;
    /**
     * The path to the node where a search should start.
     */
    LDAPSearchSettingSearchBase: string;
    /**
     * The type of recursion to use in the search. It is one of the following values:
     * * 'LDAPSearchSettingScopeBase': Only the immediate node that the search base points to.
     * * 'LDAPSearchSettingScopeOneLevel': The node plus its immediate children.
     * * 'LDAPSearchSettingScopeSubtree': The node plus all children, regardless of depth.
     */
    LDAPSearchSettingScope?:
      | "LDAPSearchSettingScopeBase"
      | "LDAPSearchSettingScopeOneLevel"
      | "LDAPSearchSettingScopeSubtree";
  }[];
  /**
   * The VPNUUID of the per-app VPN the account uses for network communication.
   * Available in iOS 14 and later.
   */
  VPNUUID?: string;
}
