/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to place an Apple TV device into Conference Room Display mode.
 */
export interface ComAppleConferenceroomdisplay {
  /**
   * The custom message displayed on the screen in Conference Room Display mode.
   */
  Message?: string;
}
