/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleManagedClientPreferences {
  /**
   * The dictionary containing app preference domains.
   */
  PreferenceDomain: {
    /**
     * The dictionary of forced settings.
     */
    Forced: {
      /**
       * The dictionary of settings.
       */
      mcx_preference_settings: {
        /**
         * The setting/value pairs.
         */
        ANY?: string;
      };
    }[];
    /**
     * The dictionary of one-time settings.
     */
    "Set-Once": {
      /**
       * The dictionary of settings.
       */
      mcx_preference_settings: {
        /**
         * The setting/value pairs.
         */
        ANY?: string;
      };
    }[];
  };
}
