/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleFamilycontrolsTimelimitsV2 {
  /**
   * If 'true', enables time limits.
   */
  familyControlsEnabled: boolean;
  /**
   * The time limits to enforce if 'familyControlsEnabled' is enabled.
   */
  "time-limits"?: {
    /**
     * The weekday allowance settings.
     */
    "weekday-allowance"?: {
      /**
       * If 'true', enable these settings.
       */
      enabled: boolean;
      /**
       * The type of day range:
       * 0 = Weekday
       * 1 = Weekend
       */
      rangeType: 0 | 1;
      /**
       * The curfew start time, in the format '%d:%d:%d'.
       */
      start?: string;
      /**
       * The curfew end time, in the format '%d:%d:%d'.
       */
      end?: string;
      /**
       * The allowance for that day, in seconds.
       */
      secondsPerDay?: number;
    };
    /**
     * The weekday curfew settings.
     */
    "weekday-curfew"?: {
      /**
       * If 'true', enable these settings.
       */
      enabled: boolean;
      /**
       * The type of day range:
       * 0 = Weekday
       * 1 = Weekend
       */
      rangeType: 0 | 1;
      /**
       * The curfew start time, in the format '%d:%d:%d'.
       */
      start?: string;
      /**
       * The curfew end time, in the format '%d:%d:%d'.
       */
      end?: string;
      /**
       * The allowance for that day, in seconds.
       */
      secondsPerDay?: number;
    };
    /**
     * The weekend allowance settings.
     */
    "weekend-allowance"?: {
      /**
       * If 'true', enable these settings.
       */
      enabled: boolean;
      /**
       * The type of day range:
       * 0 = Weekday
       * 1 = Weekend
       */
      rangeType: 0 | 1;
      /**
       * The curfew start time, in the format '%d:%d:%d'.
       */
      start?: string;
      /**
       * The curfew end time, in the format '%d:%d:%d'.
       */
      end?: string;
      /**
       * The allowance for that day, in seconds.
       */
      secondsPerDay?: number;
    };
    /**
     * The weekend curfew settings.
     */
    "weekend-curfew"?: {
      /**
       * If 'true', enable these settings.
       */
      enabled: boolean;
      /**
       * The type of day range:
       * 0 = Weekday
       * 1 = Weekend
       */
      rangeType: 0 | 1;
      /**
       * The curfew start time, in the format '%d:%d:%d'.
       */
      start?: string;
      /**
       * The curfew end time, in the format '%d:%d:%d'.
       */
      end?: string;
      /**
       * The allowance for that day, in seconds.
       */
      secondsPerDay?: number;
    };
  };
}
