/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleSystemuiserver {
  /**
   * The media type dictionary that defines volumes to eject when the user logs out.
   */
  "logout-eject"?: {
    /**
     * Unused; set to an empty string.
     */
    "all-media"?: string;
    /**
     * A media action string or an array of media action strings.
     */
    cd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    dvd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    bd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankcd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankdvd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankbd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    dvdram?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    "disk-image"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    "harddisk-internal"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A string or an array of media action strings. Internally installed SD cards and USB flash drives are included in the hard disk-external category.
     *
     * This key is the default for media types that don't fall into other categories.
     */
    "harddisk-external"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    networkdisk?: ("authenticate" | "read-only" | "deny" | "eject")[];
  };
  /**
   * The media type dictionary that controls volume mounting.
   */
  "mount-controls"?: {
    /**
     * Unused; set to an empty string.
     */
    "all-media"?: string;
    /**
     * A media action string or an array of media action strings.
     */
    cd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    dvd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    bd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankcd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankdvd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankbd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    dvdram?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    "disk-image"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    "harddisk-internal"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A string or an array of media action strings. Internally installed SD cards and USB flash drives are included in the hard disk-external category.
     *
     * This key is the default for media types that don't fall into other categories.
     */
    "harddisk-external"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    networkdisk?: ("authenticate" | "read-only" | "deny" | "eject")[];
  };
  /**
   * The media type dictionary that controls volume unmounting.
   */
  "unmount-controls"?: {
    /**
     * Unused; set to an empty string.
     */
    "all-media"?: string;
    /**
     * A media action string or an array of media action strings.
     */
    cd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    dvd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    bd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankcd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankdvd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    blankbd?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    dvdram?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    "disk-image"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    "harddisk-internal"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A string or an array of media action strings. Internally installed SD cards and USB flash drives are included in the hard disk-external category.
     *
     * This key is the default for media types that don't fall into other categories.
     */
    "harddisk-external"?: ("authenticate" | "read-only" | "deny" | "eject")[];
    /**
     * A media action string or an array of media action strings.
     */
    networkdisk?: ("authenticate" | "read-only" | "deny" | "eject")[];
  };
}
