/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleSystempolicyRule {
  /**
   * The policy requirement. This key must follow the syntax described in Code Signing Requirement Language <https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/RequirementLang/RequirementLang.html#//apple_ref/doc/uid/TP40005929-CH5>.
   */
  Requirement?: string;
  /**
   * This string appears in the System Policy UI. If it's missing, 'PayloadDisplayName' or 'PayloadDescription' is entered into this field before the rule is added to the System Policy database.
   */
  Comment?: string;
  /**
   * The rule's priority.
   */
  Priority?: number;
  /**
   * The expiration date for rules being processed.
   */
  Expiration?: string;
  /**
   * The type of operation.
   */
  OperationType?: "operation:execute" | "operation:install" | "operation:lsopen";
  /**
   * The single leaf certificate for the app that is in the allow list.
   */
  LeafCertificate?: string;
}
