/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleSystempolicyControl {
  /**
   * If 'true', enables Gatekeeper.
   */
  EnableAssessment?: boolean;
  /**
   * If 'true', enables Gatekeeper's 'Mac App Store and identified developers' option.
   * If 'false', enables Gatekeeper's 'Mac App Store' option.
   * If the value of 'EnableAssessment' isn't set to 'true', this key has no effect.
   */
  AllowIdentifiedDevelopers?: boolean;
}
