/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleShareKitHelper {
  /**
   * The list of plugin IDs that show up in the user's Share menu. If this array exists, only these items are permitted.
   */
  SHKAllowedShareServices?: string[];
  /**
   * The list of plugin IDs that won't show up in the user's Share menu. This key is used only if there is no 'SHKAllowedShareServices' key.
   */
  SHKDeniedShareServices?: string[];
}
