/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for certificate revocation.
 */
export interface ComAppleSecurityCertificaterevocation {
  /**
   * An array of certificates that the system checks for revocation.
   * Specifying a certificate authority (CA) enables revocation checking for all certificates chaining up to that CA.
   * It is not necessary to specify trusted root certificates because they are implicitly specified. See <https://support.apple.com/en-us/HT209143> for the available trusted root certificates for Apple operating systems.
   */
  EnabledForCerts?: {
    /**
     * The algorithm must be 'sha256'.
     */
    Algorithm: "sha256";
    /**
     * The hash of the DER-encoding of the certificate's 'subjectPublicKeyInfo'.
     * The hash field requires the data ('subjectPublicKeyInfo' hash) in a specific format: a Base64 encoded (binary) SHA-256 hash of the certificate's public key.
     */
    Hash: string;
  }[];
}
