/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Payload dictionary keys common to all payload types
 */
export interface CommonPayloadKeys {
  /**
   * The reverse-DNS-style identifier for the payload. This identifier is usually the same as the TopLevel value, with an additional appended component. This string must be unique within the profile.
   * During a profile replacement, the system updates payloads with the same 'PayloadIdentifier' and 'PayloadUUID' in the old and new profiles.
   */
  PayloadIdentifier: string;
  /**
   * The globally unique identifier for the payload. The actual content is unimportant, but must be globally unique. In macOS, use 'uuidgen' to generate UUIDs.
   * During a profile replacement, the system updates payloads with the same 'PayloadIdentifier' and 'PayloadUUID' in the old and new profiles.
   */
  PayloadUUID: string;
  /**
   * The payload type, which each payload domain's reference page specifies.
   */
  PayloadType: string;
  /**
   * The version of this specific payload.
   */
  PayloadVersion: 1;
  /**
   * The human-readable description of this payload. This description appears on the Detail screen.
   */
  PayloadDescription?: string;
  /**
   * The human-readable name for the profile payload. The name appears on the Detail screen and doesn't need to be unique.
   */
  PayloadDisplayName?: string;
  /**
   * The human-readable string containing the name of the organization that provides the profile. This value doesn't need to match the organization payload value in the enclosing dictionary.
   */
  PayloadOrganization?: string;
}
