/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to turn on the Declarative Management engine on the device (the first time it is used), or to trigger a Declarative Management synchronization operation.
 */
export interface DeclarativeManagementCommand {
  /**
   * The base64-encoded Declarative Management JSON request using a TokensResponse.
   */
  Data?: string;
}
