/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command requires the Device Lock access right. The device will restart immediately.
 */
export interface DeviceRestartCommand {
  /**
   * If 'true', the system rebuilds the kernel cache during a device restart. If 'BootstrapTokenAllowedForAuthentication' is 'true' in the SecurityInfoResponse.SecurityInfo response, the device requests the bootstrap token from the MDM server prior to executing this command. This value is available in macOS 11 and later.
   */
  RebuildKernelCache?: boolean;
  /**
   * If 'RebuildKernelCache' is 'true', this value specifies the paths to kexts to add to the auxiliary kernel cache since the last kernel cache rebuild. If not present, the system only adds previously discovered kexts to the kernel cache. This value is available in macOS 11 and later.
   */
  KextPaths?: string[];
  /**
   * If 'true', notifies the user to restart the device at their convenience. No forced restart occurs unless the device is at 'loginwindow' with no logged-in users. The user can dismiss the notification and ignore the request. No further notifications display unless you resend the command.
   * This value is available in macOS 11.3 and later.
   */
  NotifyUser?: boolean;
}
