/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to immediately lock the device. This command requires the Device Lock and Passcode Removal right.
 */
export interface DeviceLockCommand {
  PayloadKeys?: {
    /**
     * The message to display on the Lock screen of the device. This value doesn't apply to a shared iPad device. This value is available in iOS 4 and later, and macOS 10.14 and later.
     */
    Message?: string;
    /**
     * The phone number to display on the Lock screen. This value doesn't apply to a shared iPad device. This value is available in iOS 7 and later and macOS 11.5 and later (for Apple silicon devices only).
     */
    PhoneNumber?: string;
    /**
     * The six-character PIN for Find My. This value is available in macOS 10.8 and later.
     */
    PIN?: string;
  };
  ResponseKeys?: {
    /**
     * The message result if the command includes a message or phone number, which is one of the following values:
     * * 'Success': The message displayed successfully.
     * * 'DeviceInLostMode': The device is in Lost Mode.
     * * 'NoPasscodeSet': The message didn't display because there isn't a set passcode.
     * * 'Unknown': An unknown error occurred.
     */
    MessageResult?: string;
  };
}
