/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to query for specific device information. It's supported in the user channel.
 */
export interface DeviceInformationCommand {
  PayloadKeys?: {
    /**
     * An array of query dictionaries to get information about a device.
     */
    Queries?: string[];
    /**
     * This value can contain up to 32 bytes of data. If specified, queries need to contain 'DevicePropertiesAttestation'. If omitted or if the value matches the cached attestation, the system returns the cached attestation. Otherwise, the system requests and returns a new attestation that contains the new nonce.
     * The nonce appears in the resulting attestation to ensure it was recently generated. To request a new attestation, provide a new nonce. The system caches the most recently generated attestation on the device. Requests for new attestations are rate limited. If it has been fewer than 7 days since the system generated an attestation, the device returns the cached attestation rather than generating a new one.
     */
    DeviceAttestationNonce?: string;
  };
  ResponseKeys?: {
    /**
     * A dictionary that contains information about the device.
     */
    QueryResponses: {
      /**
       * The unique identifier of the device.
       */
      UDID?: string;
      /**
       * The device identifier used in provisioning profiles. This value differs from the UDID on Macs with Apple silicon. Available in macOS 11.3 and later.
       */
      ProvisioningUDID?: string;
      /**
       * The contents of SettingsCommand.Command.Settings.OrganizationInfo.OrganizationInfo.
       */
      OrganizationInfo?: {
        /**
         * A string that describes the organization operating the MDM server. This value is available in iOS 7 and later, macOS 10.11 and later, and tvOS 9 and later.
         */
        OrganizationName: string;
        /**
         * The organization's address. Use the LF character ('&#10') to insert line breaks. This value is available in iOS 7 and later, macOS 10.11 and later, and tvOS 9 and later.
         */
        OrganizationAddress?: string;
        /**
         * The organization's phone number. This value is available in iOS 7 and later, macOS 10.11 and later, and tvOS 9 and later.
         */
        OrganizationPhone?: string;
        /**
         * The organization's support email address. This value is available in iOS 7 and later, macOS 10.11 and later, and tvOS 9 and later.
         */
        OrganizationEmail?: string;
        /**
         * A unique identifier for the various services a single organization manages. This value is available in iOS 7 and later, macOS 10.11 and later, and tvOS 9 and later.
         */
        OrganizationMagic?: string;
      };
      /**
       * The contents of SettingsCommand.Command.Settings.MDMOptions.MDMOptions.
       */
      MDMOptions?: {
        /**
         * If 'true', a supervised device registers itself with Activation Lock when the user enables Find My. Unsupervised devices ignore this value. This value is available in iOS 7 and later, macOS 11 and later, and tvOS 9 and later.
         */
        ActivationLockAllowedWhileSupervised?: boolean;
        /**
         * If 'true', the server supports Bootstrap Token commands. This value is available in macOS 11 and later.
         */
        BootstrapTokenAllowed?: boolean;
        /**
         * If 'true', the device can accept a Bootstrap Token from the MDM server instead of prompting for user authentication prior to installation. This only applies when 'BootstrapTokenAllowedForAuthentication' is 'true' in the SecurityInfoResponse.SecurityInfo response. This value is available for Apple silicon devices in macOS 11 and later.
         */
        PromptUserToAllowBootstrapTokenForAuthentication?: boolean;
      };
      /**
       * The date of the last iCloud backup. This query is available in iOS 8 and later.
       */
      LastCloudBackupDate?: string;
      /**
       * If 'true' on the device channel, the device is still waiting for a DeviceConfiguredCommand to continue through Setup Assistant.
       * If 'true' on the user channel (Shared iPad only), the device is still waiting for a UserConfiguredCommand to continue through Setup Assistant and finish login.
       */
      AwaitingConfiguration?: boolean;
      /**
       * If 'true', the device has an active iTunes Store account. This value requires the App Installation access right.
       */
      iTunesStoreAccountIsActive?: boolean;
      /**
       * A hash of the logged-in iTunes Store account. Also see GetVppUserRequest. This value requires the App Installation access right.
       */
      iTunesStoreAccountHash?: string;
      /**
       * The device name. This value requires the Device Information access right.
       */
      DeviceName?: string;
      /**
       * The operating system version. This value requires the Device Information access right.
       */
      OSVersion?: string;
      /**
       * The OS update rapid security response version letter.
       */
      SupplementalOSVersionExtra?: string;
      /**
       * The operating system version. This value requires the Device Information access right.
       */
      BuildVersion?: string;
      /**
       * The supplemental OS build version.
       */
      SupplementalBuildVersion?: string;
      /**
       * The model name, for example, iPhone. This value requires the Device Information access right.
       */
      ModelName?: string;
      /**
       * The model. This value requires the Device Information access right.
       */
      Model?: string;
      /**
       * The device's hardware model number including region info, for example, 'MK1A3LL/A'. This value requires the Device Information right, and it requires Apple silicon on macOS.
       */
      ModelNumber?: string;
      /**
       * If 'true', the macOS device uses an Apple silicon chip.
       */
      IsAppleSilicon?: boolean;
      /**
       * The product name, such as iPad8,12. This value requires the Device Information access right.
       */
      ProductName?: string;
      /**
       * The serial number. This value requires the Device Information access right.
       */
      SerialNumber?: string;
      /**
       * The total capacity in floating-point base-10 gigabytes (GB) on iOS and macOS 12 or later. The capacity is in base-2 gibibytes (GiB) on macOS 11 and earlier. This value requires the Device Information access right, and is available in iOS 4 and later, and macOS 10.7 and later.
       */
      DeviceCapacity?: number;
      /**
       * The available capacity in floating-point base-10 gigabytes (GB) on iOS and macOS 12 or later. The capacity is in base-2 gibibytes (GiB) on macOS 11 and earlier. This value requires the Device Information access right, and is available in iOS 4 and later, and macOS 10.7 and later.
       */
      AvailableDeviceCapacity?: number;
      /**
       * The International Mobile Equipment Identity (IMEI) number. This value requires the Device Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      IMEI?: string;
      /**
       * The mobile equipment identifier (MEID) number. This value requires the Device Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      MEID?: string;
      /**
       * The modem firmware version. This value requires the Device Information access right, and is available in iOS 4.0 and later.
       */
      ModemFirmwareVersion?: string;
      /**
       * The cellular technology type, which is one of the following values:
       * * '0':' 'None'
       * * '1':' 'GSM'
       * * '2':' 'CDMA'
       * * '3':' 'Both'
       * This value requires the Device Information access right, and is available in iOS 4.2.6 and later.
       */
      CellularTechnology?: 0 | 1 | 2 | 3;
      /**
       * The battery level, between '0.0' and '1.0', or '-1.0' if MDM can't determine the battery level. This value requires the Device Information access right, and is available in iOS 5 and later.
       */
      BatteryLevel?: number;
      /**
       * If 'true', the device has an internal battery.
       */
      HasBattery?: boolean;
      /**
       * If 'true', it's a supervised device. This value requires the Device Information access right, and is available in iOS 6 and later, macOS 10.15 and later, and tvOS 9 and later.
       */
      IsSupervised?: boolean;
      /**
       * If 'true', the device is in ephemeral multiuser mode. This value requires the Device Information access right, and is available in iOS 9.3 and later.
       */
      IsMultiUser?: boolean;
      /**
       * If 'true', the device has enabled a device locator service, such as Find My. This value requires the Device Information access right, and is available in iOS 7 and later.
       */
      IsDeviceLocatorServiceEnabled?: boolean;
      /**
       * If 'true', the device has enabled Activation Lock. This value requires the Device Information access right. It's available as of iOS 7 and macOS 10.9, and deprecated in iOS 16 and macOS 13.
       */
      IsActivationLockEnabled?: boolean;
      /**
       * If 'true', the device supports Activation Lock. Also see 'IsActivationLockManageable' in SecurityInfoResponse.SecurityInfo.ManagementStatus. This value is available in macOS 10.9 and later.
       */
      IsActivationLockSupported?: boolean;
      /**
       * If 'true', the device is in Do Not Disturb (DND) mode. This value is 'true' even if DND is only in effect for a locked device. This value requires the Device Information access right, and is available in iOS 7 and later.
       */
      IsDoNotDisturbInEffect?: boolean;
      /**
       * If 'true', the device can receive 'PowerON', 'PowerOFF', and 'Reset' commands from a lights-out management (LOM) controller. This query is available in macOS 11 and later.
       */
      SupportsLOMDevice?: boolean;
      /**
       * The device identifier. This value requires the Device Information access right, and is available in tvOS 6 and later.
       */
      DeviceID?: string;
      /**
       * The device identifier for Exchange Active Sync (EAS). This value requires the Device Information access right, and is available in iOS 7 and later.
       */
      EASDeviceIdentifier?: string;
      /**
       * If 'true', the device has enabled iCloud backup. This value requires the Device Information access right, and is available in iOS 7.1 and later.
       */
      IsCloudBackupEnabled?: boolean;
      /**
       * An array of the directory GUIDs of the logged-in managed users. If one of these users is currently logged in to the console, the 'CurrentConsoleManagedUser' key returns the GUID of that user. This value requires the Device Information access right, and is available in macOS 10.11 and later.
       */
      ActiveManagedUsers?: string[];
      /**
       * The contents of DeviceInformationResponse.QueryResponses.OSUpdateSettings. This value requires the Device Information access right, and is available in macOS 10.11 and later.
       */
      OSUpdateSettings?: {
        /**
         * The URL to the software update catalog the client is using. This value is available in macOS 10.11 and later.
         */
        CatalogURL?: string;
        /**
         * If 'true', 'CatalogURL' is the default catalog. This value is available in macOS 10.11 and later.
         */
        IsDefaultCatalog?: boolean;
        /**
         * The date of the last software update scan. This value is available in macOS 10.11 and later.
         */
        PreviousScanDate?: string;
        /**
         * The result code of last software update scan; '”0”' = success. This value is available in macOS 10.11 and later.
         */
        PreviousScanResult?: string;
        /**
         * If 'true', start a new scan. This value is available in macOS 10.11 and later.
         */
        PerformPeriodicCheck?: boolean;
        /**
         * The preference to automatically check for app updates. This value is available in macOS 10.11 and later.
         */
        AutoCheckEnabled?: boolean;
        /**
         * The preference to download app updates in the background. This value is available in macOS 10.11 and later.
         */
        BackgroundDownloadEnabled?: boolean;
        /**
         * The preference to automatically install app updates. This value is available in macOS 10.11 and later.
         */
        AutomaticAppInstallationEnabled?: boolean;
        /**
         * The preference to automatically install operating system updates. This value is available in macOS 10.11 and later.
         */
        AutomaticOSInstallationEnabled?: boolean;
        /**
         * The preference to automatically install system data files and security updates. This value is available in macOS 10.11 and later.
         */
        AutomaticSecurityUpdatesEnabled?: boolean;
      };
      /**
       * The local host name from Bonjour. This value is available in macOS 10.11 and later.
       */
      LocalHostName?: string;
      /**
       * The host name. This value is available in macOS 10.11 and later.
       */
      HostName?: string;
      /**
       * The contents of DeviceInformationResponse.QueryResponses.AutoSetupAdminAccountsItem, which Setup Assistant automatically created during DEP enrollment. This value requires the Device Information access right, and is available in macOS 10.11 and later.
       */
      AutoSetupAdminAccounts?: {
        /**
         * The 'GeneratedUID' of the administrator account. This value is available in macOS 10.11 and later.
         */
        GUID?: string;
        /**
         * The short name of the administrator account. This value is available in macOS 10.11 and later.
         */
        shortName?: string;
      }[];
      /**
       * If 'true', the device has enabled System Integrity Protection. This value requires the Device Information access right, and is available in macOS 10.12 and later.
       */
      SystemIntegrityProtectionEnabled?: boolean;
      /**
       * If 'true', the device has enabled Managed Lost Mode. This value requires the Device Information access right, and is available in iOS 9.3 and later.
       */
      IsMDMLostModeEnabled?: boolean;
      /**
       * The maximum number of users that can use this shared iPad device. Starting with iOS 13.4, the value that returns is always '32'. This value requires the Device Information access right, and is available in iOS 9.3 and later.
       */
      MaximumResidentUsers?: number;
      /**
       * The estimated number of users that can use this shared iPad device, according to the space available on the device and each user's quota. This value requires the Device Information access right, and is available in iOS 14 and later.
       */
      EstimatedResidentUsers?: number;
      /**
       * The quota size in megabytes for each user on this shared iPad device. This value requires the Device Information access right, and is available in iOS 13.4 and later.
       */
      QuotaSize?: number;
      /**
       * The number of users currently on this shared iPad device. This value requires the Device Information access right, and is available in iOS 13.4 and later.
       */
      ResidentUsers?: number;
      /**
       * The timeout interval for the user session. '0' means no timeout.
       */
      UserSessionTimeout?: number;
      /**
       * The timeout interval for the temporary session. '0' means no timeout.
       */
      TemporarySessionTimeout?: number;
      /**
       * If 'true', the device only allows temporary sessions.
       */
      TemporarySessionOnly?: boolean;
      /**
       * The list of domains that the device suggests on the Shared iPad login screen.
       * Available in iOS 16 and later.
       */
      ManagedAppleIDDefaultDomains?: string[];
      /**
       * The grace period for Shared iPad online authentication (in days). 0 means the device requires online authentication for every login.
       * Available in iOS 16 and later.
       */
      OnlineAuthenticationGracePeriod?: number;
      /**
       * If 'true', skip the language and country/region panes for new users on Shared iPad.
       */
      SkipLanguageAndLocaleSetupForNewUsers?: boolean;
      /**
       * The push token for the user-channel connection, in the same format as in TokenUpdateRequest. MDM ignores this query for the device channel. This value requires the Device Information access right, and is available in iOS 9.3 and later, and macOS 10.12 and later.
       */
      PushToken?: string;
      /**
       * If 'true', the device has enabled diagnostic submission. This value requires the Device Information access right, and is available in iOS 9.3 and later.
       */
      DiagnosticSubmissionEnabled?: boolean;
      /**
       * If 'true', the device is sharing app analytics. This value requires the Device Information access right, and is available in iOS 9.3 and later.
       */
      AppAnalyticsEnabled?: boolean;
      /**
       * The current Internet Assigned Numbers Authority (IANA) time zone database name. This value requires the Device Information access right, and is available in iOS 14 and later, and tvOS 14 and later.
       */
      TimeZone?: string;
      /**
       * The integrated circuit card (ICC) identifier for the installed SIM card. This value requires the Network Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      ICCID?: string;
      /**
       * The Bluetooth media access control (MAC) address. This value requires the Network Information access right.
       */
      BluetoothMAC?: string;
      /**
       * The Wi-Fi MAC address. This value requires the Network Information access right.
       */
      WiFiMAC?: string;
      /**
       * The primary Ethernet MAC address. This value requires the Network Information access right, and is available in macOS 10.7 and later.
       */
      EthernetMAC?: string;
      /**
       * The name of the current carrier network. This value requires the Network Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      CurrentCarrierNetwork?: string;
      /**
       * Apple no longer supports this query. Use 'SubscriberCarrierNetwork' instead.
       */
      SIMCarrierNetwork?: string;
      /**
       * The name of the home carrier network. This value requires the Network Information access right. It's available as of iOS 5 and deprecated in iOS 16.
       */
      SubscriberCarrierNetwork?: string;
      /**
       * The version of the carrier settings. This value requires the Network Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      CarrierSettingsVersion?: string;
      /**
       * The raw phone number without punctuation and including the country code. This value requires the Network Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      PhoneNumber?: string;
      /**
       * If 'true', the device has enabled data roaming. This value requires the Network Information access right, and is available in iOS 5 and later.
       */
      DataRoamingEnabled?: boolean;
      /**
       * If 'true', the device has enabled voice roaming, which isn't available for all carriers. This value requires the Network Information access right. It's available as of iOS 5 and deprecated in iOS 16.
       */
      VoiceRoamingEnabled?: boolean;
      /**
       * If 'true,' the device has enabled Personal Hotspot, which isn't available for all carriers. This value requires the Network Information access right, and is available in iOS 7.0 and later.
       */
      PersonalHotspotEnabled?: boolean;
      /**
       * If 'true', the device is network-tethered. This value requires the Network Information access right, and is available in iOS 10.3 and later.
       */
      IsNetworkTethered?: boolean;
      /**
       * If 'true', the device is roaming. This value requires the Network Information access right. It's available as of iOS 4.2 and deprecated in iOS 16.
       */
      IsRoaming?: boolean;
      /**
       * Apple no longer supports this query. Use 'SubscriberMCC' instead.
       */
      SIMMCC?: string;
      /**
       * Apple no longer supports this query. Use 'SubscriberMNC' instead.
       */
      SIMMNC?: string;
      /**
       * The home Mobile Country Code (MCC). This value requires the Network Information access right. It's available as of iOS 4.2.6 and deprecated in iOS 16.
       */
      SubscriberMCC?: string;
      /**
       * The key to get the home Mobile Network Code (MNC). This value requires the Network Information access right. It's available as of iOS 4.2.6 and deprecated in iOS 16.
       */
      SubscriberMNC?: string;
      /**
       * The current mobile country code (MCC).This value requires the Network Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      CurrentMCC?: string;
      /**
       * The current mobile network code (MNC). This value requires the Network Information access right. It's available as of iOS 4 and deprecated in iOS 16.
       */
      CurrentMNC?: string;
      /**
       * The contents of DeviceInformationResponse.QueryResponses.ServiceSubscriptionProperty. This value requires the Network Information access right.
       */
      ServiceSubscriptions?: {
        /**
         * The version of the carrier settings. This value is available in iOS 12 and later.
         */
        CarrierSettingsVersion?: string;
        /**
         * The name of the current carrier network. This value is available in iOS 12 and later.
         */
        CurrentCarrierNetwork?: string;
        /**
         * The current mobile country code (MCC). This value is available in iOS 12 and later.
         */
        CurrentMCC?: string;
        /**
         * The current mobile network code (MNC). This value is available in iOS 12 and later.
         */
        CurrentMNC?: string;
        /**
         * The integrated circuit card identifier (ICCID) value. This value is available in iOS 12 and later.
         */
        ICCID?: string;
        /**
         * The eSIM identifier. This value is available in iOS 14 and later.
         */
        EID?: string;
        /**
         * The device International Mobile Equipment Identity (IMEI) number. This value is available in iOS 12 and later.
         */
        IMEI?: string;
        /**
         * If 'true', this subscription is the preference for data. This value is available in iOS 12 and later.
         */
        IsDataPreferred?: boolean;
        /**
         * If 'true', the phone is roaming. This value is available in iOS 12 and later.
         */
        IsRoaming?: boolean;
        /**
         * If 'true', this subscription is the preference for voice. This value is available in iOS 12 and later.
         */
        IsVoicePreferred?: boolean;
        /**
         * The label of this subscription. This value is available in iOS 12 and later.
         */
        Label?: string;
        /**
         * The unique identifier for this subscription. This value is available in iOS 12 and later.
         */
        LabelID?: string;
        /**
         * The device Mobile Equipment Identifier (MEID) number. This query is available in iOS 12 and later.
         */
        MEID?: string;
        /**
         * The raw phone number without punctuation and including country code. This value is available in iOS 12 and later.
         */
        PhoneNumber?: string;
        /**
         * The description of the slot that contains the SIM representing this subscription. This value is available in iOS 12 and later.
         */
        Slot?: string;
        /**
         * The name of the home carrier network. This value is available in iOS 16 and later.
         */
        SubscriberCarrierNetwork?: string;
      }[];
      /**
       * If 'true', the EraseDeviceCommand requires a PIN. This value is available in macOS 11 and later.
       */
      PINRequiredForEraseDevice?: boolean;
      /**
       * If 'true', the DeviceLockCommand requires a PIN. This value is available in macOS 11 and later.
       */
      PINRequiredForDeviceLock?: boolean;
      /**
       * If 'true', the device supports iOS/iPadOS app installs through MDM. This query is available in macOS 11 and later.
       */
      SupportsiOSAppInstalls?: boolean;
      /**
       * The key representing the device identifier to use when looking up available OS updates through <https://gdmf.apple.com/v2/pmv>. Available in iOS 14.5 and later.
       */
      SoftwareUpdateDeviceID?: string;
      /**
       * The device settings that control which updates appear in the Software Update pane in Settings. Available in iOS 14.5 and later.
       */
      SoftwareUpdateSettings?: {
        /**
         * Which software updates to present to the user.
         * * '0' (the default) allows all updates.
         * * '1' allows only older updates.
         * * '2' allows only newer updates.
         * No effect if the device qualifies for only a single update.
         */
        RecommendationsCadence?: number;
      };
      /**
       * The current state of settable accessibility settings. Available in iOS 16 and later.
       */
      AccessibilitySettings?: {
        /**
         * If 'true', the device has enabled bold text.
         */
        BoldTextEnabled?: boolean;
        /**
         * If 'true', the device has enabled increase contrast.
         */
        IncreaseContrastEnabled?: boolean;
        /**
         * If 'true', the device has enabled reduced motion.
         */
        ReduceMotionEnabled?: boolean;
        /**
         * If 'true', the device has enabled reduced transparency.
         */
        ReduceTransparencyEnabled?: boolean;
        /**
         * The accessibility text size apps that support dynamic text use. 0 is the smallest value, and 11 is the largest available.
         * '-1' indicates that the current size is unknown or hasn't been explicitly set.
         */
        TextSize?: -1 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
        /**
         * If 'true', the device has enabled touch accommodations.
         */
        TouchAccommodationsEnabled?: boolean;
        /**
         * If 'true', the device has enabled voiceover.
         */
        VoiceOverEnabled?: boolean;
        /**
         * If 'true', the device has enabled zoom.
         */
        ZoomEnabled?: boolean;
        /**
         * If 'true', the device has enabled grayscale display.
         */
        GrayscaleEnabled?: boolean;
      };
      /**
       * The key to get an attestation of the device's properties. Available in iOS 16 and later, macOS 14 and later, tvOS 16 and later, and watchOS 10 and later.
       */
      DevicePropertiesAttestation?: string[];
      /**
       * Specifies whether the device can perform an EraseDeviceCommand using Erase All Content and Settings (EACS).
       * Responses can include:
       * · 'success': The device supports EACS
       * · 'not supported': The device is too old to support EACS
       * · 'unknown failure': A problem occurred for which there isn't a more specific error message
       * · '(other string)': A reason why the device can't perform EACS, for example, “System is not sealed”
       */
      EACSPreflight?: string;
    };
  };
}
