/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Instructs the device to query for active cellular plan eSIM "profiles" at the designated carrier eSIM server URL.
 */
export interface ESIMCellularPlanManagementCommand {
  /**
   * The carrier's eSIM server URL to query. Obtain this URL from each carrier separately.
   */
  eSIMServerURL: string;
}
