/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface Loginwindow {
  /**
   * If 'true', prevents the user from disabling login item launches by using the Shift key.
   */
  DisableLoginItemsSuppression?: boolean;
}
