/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Issues LOM requests to devices.
 */
export interface LOMDeviceRequestCommand {
  PayloadKeys?: {
    /**
     * An array of requests to perform.
     */
    RequestList?: {
      /**
       * The requested action to perform on the device.
       */
      DeviceRequestType: "PowerON" | "PowerOFF" | "Reset";
      /**
       * The unique identifier of the request.
       */
      DeviceRequestUUID: string;
      /**
       * The DNS name of the device. This should match the 'dNSName' in SCEP.PayloadContent.SubjectAltName or an equivalent in a PKCS12 identity.
       */
      DeviceDNSName: string;
      /**
       * An array that contains the IPv6 addresses for primary LOM-compatible Ethernet interfaces for the device.
       */
      PrimaryIPv6AddressList: string[];
      /**
       * An array that contains the IPv6 addresses for secondary LOM-compatible Ethernet interfaces for the device.
       */
      SecondaryIPv6AddressList: string[];
      /**
       * The LOM protocol version that the device supports. Provide the same value that 'LOMProtocolVersion' receives in the LOMSetupRequestResponse.
       */
      LOMProtocolVersion: number;
    }[];
  };
  ResponseKeys?: {
    /**
     * An array of dictionaries that describes the status of each request.
     */
    ResponseList: {
      /**
       * If 'true', the request was successful.
       */
      DeviceRequestSuccess: boolean;
      /**
       * The unique identifier of the request for this response list item.
       */
      DeviceRequestUUID: string;
      /**
       * If present, a description of the error for a failed request.
       */
      DeviceRequestReturnError?: string;
    }[];
  };
}
