/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command returns information about installed extensions for a user.
 */
export interface NSExtensionsMappingsNSExtensions {
  PayloadKeys?: {};
  ResponseKeys?: {
    /**
     * An array of dictionaries that contains information about extensions on the device.
     */
    Extensions: {
      /**
       * The identifier of the extension.
       */
      Identifier: string;
      /**
       * The NSExtensionPointIdentifier for the extension.
       */
      ExtensionPoint: string;
      /**
       * The display name of the extension.
       */
      DisplayName: string;
    }[];
  };
}
