/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows a server to remove a managed app.
 */
export interface RemoveApplicationCommand {
  /**
   * The bundle identifier of the managed app.
   */
  Identifier: string;
}
