/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command requests an UnlockToken from the device.
 */
export interface RequestUnlockTokenCommand {
  PayloadKeys?: {};
  ResponseKeys?: {
    /**
     * The unlock token. Erasing the user partition invalidates this token.
     */
    UnlockToken: string;
  };
}
