/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this configuration to define a connection to a Screen Sharing host.
 */
export interface ScreenSharingConnection {
  /**
   * A unique identifier for this connection when it's in a connection group.
   */
  ConnectionUUID: string;
  /**
   * The name of the connection.
   */
  DisplayName: string;
  /**
   * The host name or IP address of the Mac that hosts the screen-sharing connection.
   */
  HostName: string;
  /**
   * Specifies the TCP port number on the host to initiate the connection.
   */
  Port?: number;
  /**
   * The display configuration for this connection.
   */
  DisplayConfiguration: {
    /**
     * The type of display for the connection, which has these allowed values:
     * * 'Virtual1': Create one virtual display.
     * * 'Virtual2': Create two virtual displays.
     */
    DisplayType: "Virtual1" | "Virtual2";
  };
  /**
   * Specifies the identifier of an asset declaration that contains the required credentials for this connection to authenticate with the screen-sharing server. Set the corresponding asset type to 'com.apple.asset.credential.userpassword'.
   */
  AuthenticationCredentialsAssetReference?: string;
}
