/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this configuration to add a certificate to the device.
 */
export interface SecurityCertificate {
  /**
   * Specifies the identifier of an asset declaration that contains the certificate to install.
   */
  CredentialAssetReference: string;
}
