/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command queries the device for security-related information. Queries are available if the MDM host has the Security Query right.
 */
export interface SecurityInformationCommand {
  PayloadKeys?: {};
  ResponseKeys?: {
    /**
     * A dictionary that contains security-related information.
     */
    SecurityInfo: {
      /**
       * An integer that indicates the underlying hardware encryption capabilities of the device, which is one of the following values:
       * * '1': Block-level encryption
       * * '2': File-level encryption
       * * '3': Both block-level and file-level encryption
       * For a device to have data protection, 'HardwareEncryptionCaps' must be '3' and 'PasscodePresent' must 'true'.
       * This value is available in iOS 4 and later, and tvOS 6 and later.
       */
      HardwareEncryptionCaps?: number;
      /**
       * If 'true', the device has a passcode. This value is available in iOS 4 and later, and tvOS 6 and later.
       */
      PasscodePresent?: boolean;
      /**
       * If 'true', the user's passcode is compliant with all requirements on the device, including Exchange and other accounts. This value is available in iOS 4 and later, and tvOS 6 and later.
       */
      PasscodeCompliant?: boolean;
      /**
       * If 'true', the user's passcode is compliant with requirements from profiles. This key does not apply to User-Enrolled devices. This value is available in iOS 4 and later, and tvOS 6 and later.
       */
      PasscodeCompliantWithProfiles?: boolean;
      /**
       * The user preference for the number of seconds before a locked screen requires the device passcode to unlock it. This value is only available for Shared iPad.
       */
      PasscodeLockGracePeriod?: number;
      /**
       * The enforced value for the number of seconds before a locked screen requires the device passcode to unlock it. If a device has a passcode, changing 'PasscodeLockGracePeriod' to a larger value doesn't take effect until the user logs out or removes the passcode. This value is only available for Shared iPad.
       */
      PasscodeLockGracePeriodEnforced?: number;
      /**
       * The number of seconds before a device goes to sleep after being idle. This value is only available for Shared iPad.
       */
      AutoLockTime?: number;
      /**
       * If 'true', the device has enabled FileVault full disk encryption (FDE). This value is available in macOS 10.9 and later.
       */
      FDE_Enabled?: boolean;
      /**
       * If 'true', FileVault FDE has a personal recovery key. This value is available in macOS 10.9 and later.
       */
      FDE_HasPersonalRecoveryKey?: boolean;
      /**
       * If 'true', FileVault FDE has an institutional recovery key. This value is available in macOS 10.9 and later.
       */
      FDE_HasInstitutionalRecoveryKey?: boolean;
      /**
       * If the FileVault personal recovery key has enabled escrow with a recovery key, this value contains the key. The certificate from the FDERecoveryKeyEscrow profile encrypts the key and wraps it as CMS data. This value is available in macOS 10.13 and later.
       */
      FDE_PersonalRecoveryKeyCMS?: string;
      /**
       * If the FileVault personal recovery key has enabled escrow with a recovery key, this value is the device serial number. This is the value that displays to the user at the EFI login window as part of the help message if they enter their password incorrectly three times. The server also uses this value as an index when saving the device personal recovery key. This replaces the 'recordNumber' that the server returned in the previous escrow mechanism. This value is available in macOS 10.13 and later.
       */
      FDE_PersonalRecoveryKeyDeviceKey?: string;
      /**
       * If 'true', System Integrity Protection (SIP) is active on the device. This value is available in macOS 10.12 and later.
       */
      SystemIntegrityProtectionEnabled?: boolean;
      /**
       * A dictionary that contains the firewall settings. This value is available in macOS 10.12 and later.
       */
      FirewallSettings?: {
        /**
         * If 'true', the firewall is on.
         */
        FirewallEnabled?: boolean;
        /**
         * If 'true', the firewall blocks all incoming connections.
         */
        BlockAllIncoming?: boolean;
        /**
         * If true, stealth mode is active for the firewall.
         */
        StealthMode?: boolean;
        /**
         * An array of dictionaries that describes the allowed applications.
         */
        Applications?: {
          /**
           * If 'true', the app is an allowed app.
           */
          Allowed?: boolean;
          /**
           * The app's bundle identifier.
           */
          BundleID?: string;
          /**
           * The app's display name if it's determinable from the 'BundleID'.
           */
          Name?: string;
        }[];
        /**
         * If 'true', logging is enabled.
         */
        LoggingEnabled?: boolean;
        /**
         * The type of logging emitted by the firewall.
         */
        LoggingOption?: "throttled" | "brief" | "detail";
      };
      /**
       * A dictionary that contains the status of the EFI firmware password. This value is available in macOS 10.13 and later.
       */
      FirmwarePasswordStatus?: {
        /**
         * If 'true', the device has an EFI firmware password.
         */
        PasswordExists?: boolean;
        /**
         * If 'true', a firmware password change is pending. A device restart is necessary for this change to take effect. Until then, additional attempts to change the password fail.
         * If 'true', the other values show the current state of the device, not the state after a restart.
         */
        ChangePending?: boolean;
        /**
         * If 'true', enable ROMs.
         */
        AllowOroms?: boolean;
      };
      /**
       * A dictionary that contains the status of the device's MDM enrollment.
       */
      ManagementStatus?: {
        /**
         * If 'true', the device enrolled in MDM through the Device Enrollment Program (DEP). This value is available in macOS 10.13.2 and later.
         */
        EnrolledViaDEP?: boolean;
        /**
         * If 'true', the enrollment was user-approved. If 'false', the device may reject certain security-sensitive payloads or commands. This value is available in macOS 10.13.2 and later.
         */
        UserApprovedEnrollment?: boolean;
        /**
         * If 'true', the device is user-enrolled. This value is available in iOS 13 and later, and macOS 10.15 and later.
         */
        IsUserEnrollment?: boolean;
        /**
         * If 'true', the type of enrollment allows the MDM to manage Activation Lock for this device. This value is available in macOS 10.15 and later.
         */
        IsActivationLockManageable?: boolean;
      };
      /**
       * A dictionary that contains the device's Secure Boot settings. This value is available in macOS 10.15 and later.
       */
      SecureBoot?: {
        /**
         * The security level for the bootable operating system versions.
         */
        SecureBootLevel?: "off" | "medium" | "full" | "not supported";
        /**
         * The device's external boot level, which indicates whether it allows booting from an external device, disallows it, or doesn't support it.
         */
        ExternalBootLevel?: "allowed" | "disallowed" | "not supported";
        /**
         * Reports which security features the user disables in 'recoveryOS'. This property is only present for Apple silicon when 'SecureBootLevel' is 'medium'.
         * Available in iOS 11 and later.
         */
        ReducedSecurity?: string[];
      };
      /**
       * If 'true', Remote Desktop is active on the device. This value is available in macOS 10.14.4 and later.
       */
      RemoteDesktopEnabled?: boolean;
      /**
       * If 'true', the system booted using an Authenticated Root Volume. This value is available in macOS 11 and later.
       */
      AuthenticatedRootVolumeEnabled?: boolean;
      /**
       * This value specifies whether the Secure Enclave Processor (SEP) supports and allows secure operations to use the Bootstrap Token. The value is automatically set for devices enrolled through the Device Enrollment Program (DEP). The user can also manually set this value in the RecoveryOS.
       * This value is available for Apple silicon in macOS 11 and later. Not available for user enrollment.
       */
      BootstrapTokenAllowedForAuthentication?: "allowed" | "disallowed" | "not supported";
      /**
       * If 'true', the device can accept a Bootstrap Token from the MDM server instead of prompting for user authentication prior to installation. This only applies when 'BootstrapTokenAllowedForAuthentication' is 'true' in the SecurityInfoResponse.SecurityInfo response.
       * This value is available for Apple silicon in macOS 11 and later. Not available for user enrollment.
       */
      BootstrapTokenRequiredForSoftwareUpdate?: boolean;
      /**
       * If 'true', the device can accept a Bootstrap Token from the MDM server instead of prompting for user authentication prior to enabling kernel extensions. This includes enabling kexts through the 'com.apple.syspolicy.kernel-extension-policy' payload or triggering the 'RestartDevice' command with 'RebuildKernelCache' set to 'true'. This only applies when 'BootstrapTokenAllowedForAuthentication' is 'true' in the SecurityInfoResponse.SecurityInfo response.
       * This value is available for Apple silicon in macOS 11 and later. Not available for user enrollment.
       */
      BootstrapTokenRequiredForKernelExtensionApproval?: boolean;
      /**
       * If 'true', a password is required to enter recovery (see SetRecoveryLockCommand). Available in macOS 11.5 and later and only on Apple silicon devices.
       */
      IsRecoveryLockEnabled?: boolean;
    };
  };
}
