/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Specifies managed configuration files for services
 */
export interface ServicesConfigurationFiles {
  /**
   * The identifier of the system service with managed configuration files.
   * Use a reverse DNS style for this identifier. However, the system reserves 'com.apple.' prefix for built-in services.
   * The available built-in services are:
   * * 'com.apple.sshd' configures sshd
   * * 'com.apple.sudo' configures sudo
   * * 'com.apple.pam' configures PAM
   * * 'com.apple.cups' configures CUPS
   * * 'com.apple.apache.httpd' configures Apache httpd
   * * 'com.apple.bash' configures bash
   * * 'com.apple.zsh' configures zsh
   */
  ServiceType: string;
  /**
   * Specifies the identifier of an asset declaration that contains a reference to the files to use for system service configuration. Ensure that the corresponding asset:
   * * Is of type 'com.apple.asset.data'
   * * Is a zip archive of an entire directory
   * * Has a 'Reference' key that includes the 'ContentType' and 'Hash-SHA-256' keys, which the system requires
   * The system expands the zip archive and stores the data in a well-known location for the service.
   */
  DataAssetReference: string;
}
