/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Sets or clears the recovery lock password (AppleSilicon devices only)
 */
export interface SetRecoveryLockCommand {
  /**
   * If the device has a Recovery Lock password set, the system requires the current password.
   */
  CurrentPassword?: string;
  /**
   * The new password for Recovery Lock. Set as an empty string to clear the Recovery Lock password.
   */
  NewPassword: string;
}
