/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to unlock a local user account.
 */
export interface UnlockUserAccountCommand {
  /**
   * The user name of the local account, which can be any local account on the system, not just a managed user account.
   */
  UserName: string;
}
