/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Specifies an MDMv1 Apple Watch enrollment profile
 */
export interface WatchEnrollment {
  /**
   * The URL of the profile that the Apple Watch downloads and installs if the user opts in to management during the pairing process, which needs to start with 'https://'. Successful enrollment requires that the pairing iPhone is supervised and the profile contains an MDM payload. Apple Watch attempts to install each payload that the profile contains.
   */
  EnrollmentProfileURL: string;
  /**
   * Specifies an array of identifiers of asset declarations that contain anchor certificates to use to evaluate the trust of the enrollment profile server. Set the type of the corresponding assets to 'com.apple.asset.credential.certificate'.
   */
  AnchorCertificateAssetReferences?: string[];
}
