/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command can be sent to the device to have it create the local administrator account (thereby skipping the page to create this account in Setup Assistant)
 */
export interface AccountConfigurationCommand {
  /**
   * If 'true', Setup Assistant skips the user interface for setting up primary accounts and disables autologin. If 'true', you must specify a value for 'AutoSetupAdminAccounts'.
   */
  SkipPrimarySetupAccountCreation?: boolean;
  /**
   * If 'true', Setup Assistant creates the primary accounts as regular users, and you must specify a value for 'AutoSetupAdminAccounts'.
   */
  SetPrimarySetupAccountAsRegularUser?: boolean;
  /**
   * The full name for the primary account. If present, Setup Assistant uses this value to prefill the Full Name field. However, Setup Assistant ignores this value if 'DontAutoPopulatePrimaryAccountInfo' is 'true'. This value is available in macOS 10.15 and later.
   */
  PrimaryAccountFullName?: string;
  /**
   * The account name for the primary account. If present, Setup Assistant uses this value to prefill the User Name field. However, Setup Assistant ignores this value if 'DontAutoPopulatePrimaryAccountInfo' is 'true'. This value is available in macOS 10.15 and later.
   */
  PrimaryAccountUserName?: string;
  /**
   * If 'true', Setup Assistant ignores the primary account information and requires the user to enter that information. If 'false', Setup Assistant prefills the Full Name field with 'PrimaryAccountFullName' and the User Name field with 'PrimaryAccountUserName'. This value is available in macOS 10.15 and later.
   */
  DontAutoPopulatePrimaryAccountInfo?: boolean;
  /**
   * If 'true', and you provide values for 'PrimaryAccountFullName' or 'PrimaryAccountUserName', Setup Assistant disables editing for the corresponding fields. 'DontAutoPopulatePrimaryAccountInfo' must also be 0 (or missing).
   * If the user's password is also available from authentication via ConfigurationURL, Setup Assistant automatically creates the primary account with that information and skips showing the user interface to view or edit these fields.
   * This value is available in macOS 10.15 and later.
   */
  LockPrimaryAccountInfo?: boolean;
  /**
   * A dictionary that describes the administrator account to create with Setup Assistant, which uses the first element and ignores additional elements.
   */
  AutoSetupAdminAccounts?: {
    /**
     * The short name of the user.
     */
    shortName: string;
    /**
     * The full name of the user, which defaults to 'shortName' if not specified.
     */
    fullName?: string;
    /**
     * Data that contains the pre-created salted PBKDF2 SHA512 password hash for the account.
     */
    passwordHash?: string;
    /**
     * If 'true', this sets the account attribute to make the account hidden in the login window and Users & Groups.
     */
    hidden?: boolean;
  }[];
  /**
   * If present, this is the short name of the local account to manage, which can also be the account that results from setting 'AutoSetupAdminAccounts' to 'true'. Otherwise, only the local account that Setup Assistant creates is a managed account. This value is available in macOS 11 and later.
   */
  ManagedLocalUserShortName?: string;
}
