/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this configuration to define settings for access to CardDAV servers.
 */
export interface AccountCardDAV {
  /**
   * The name that apps show to the user for this address book account. If not present, the system generates a suitable default.
   */
  VisibleName?: string;
  /**
   * The hostname or IP address of the CardDAV server.
   */
  HostName: string;
  /**
   * The port number for the CardDAV server.
   */
  Port?: number;
  /**
   * The path for the CardDAV server.
   */
  Path?: string;
  /**
   * The identifier of an asset declaration that contains the credentials for this account. Set the corresponding asset type to 'CredentialUserNameAndPassword'.
   */
  AuthenticationCredentialsAssetReference?: string;
}
