/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this configuration to define settings for access to LDAP servers.
 */
export interface AccountLDAP {
  /**
   * The name that apps show to the user for this LDAP account. If not present, the system generates a suitable default.
   */
  VisibleName?: string;
  /**
   * The hostname or IP address of the LDAP server.
   */
  HostName: string;
  /**
   * The port number or IP address of the LDAP server.
   */
  Port?: number;
  /**
   * The identifier of an asset declaration that contains the credentials for this account. Set the corresponding asset type to 'CredentialUserNameAndPassword'.
   */
  AuthenticationCredentialsAssetReference?: string;
  /**
   * The array of nodes to start LDAP searches from. There must be at least one node for this account to be useful. macOS only searches one node and ignores other items in the array.
   */
  SearchSettings?: {
    /**
     * The description of this search setting in the Contacts and Settings apps. If not present, the apps display no name.
     */
    VisibleDescription?: string;
    /**
     * The path to the node where a search starts. For example, 'ou=people,o=example corp'.
     */
    SearchBase: string;
    /**
     * The type of recursion to use in the search.
     * * 'Base': Only the 'SearchBase' node.
     * * 'OneLevel': The 'SearchBase' node and its immediate children.
     * * 'Subtree': The 'SearchBase' node and all its children, regardless of depth.
     */
    Scope?: "Base" | "OneLevel" | "Subtree";
  }[];
}
