/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command queries the device for the current configuration of managed applications. This command requires the App Management right. macOS supports this command as of 10.15, on the device channel and for User Enrollments only, because Settings->ApplicationConfiguration is supported. Since macOS does not support Managed Applications, this command can be used for any bundle identifier.
 */
export interface AppConfigurationCommand {
  PayloadKeys?: {
    /**
     * The bundle identifiers of the managed apps.
     * For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
     */
    Identifiers?: string[];
  };
  ResponseKeys?: {
    /**
     * An array of app configurations items.
     */
    ApplicationConfigurations: {
      /**
       * The app's bundle identifier.
       * For a watchOS app, the identifier is the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired.
       */
      Identifier: string;
      /**
       * The app's configurations.
       */
      Configuration?: {
        /**
         * The app's configuration items.
         */
        ANY?: string;
      };
    }[];
  };
}
