/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Queries managed application attributes. Attributes can be set on managed apps. These attributes can be changed over time.
 */
export interface AppAttributesCommand {
  PayloadKeys?: {
    /**
     * The bundle identifiers of the managed apps.
     * For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
     */
    Identifiers?: string[];
  };
  ResponseKeys?: {
    /**
     * An array of app attributes items.
     */
    ApplicationAttributes: {
      /**
       * The app's bundle identifier.
       * For a watchOS app, the identifier is the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired.
       */
      Identifier: string;
      /**
       * The app's attributes.
       */
      Attributes?: {
        /**
         * A per-app VPN unique identifier for this app.
         */
        VPNUUID?: string;
        /**
         * The content Filter UUID assigned to this app.
         * Available in iOS 16 and later.
         */
        ContentFilterUUID?: string;
        /**
         * The DNS Proxy UUID assigned to this app.
         * Available in iOS 16 and later.
         */
        DNSProxyUUID?: string;
        /**
         * The relay UUID for this app.
         */
        RelayUUID?: string;
        /**
         * This app's associated domains. This value is available in iOS 13 and later.
         */
        AssociatedDomains?: string[];
        /**
         * If 'true', perform claimed site association verification directly at the domain instead of on Apple's servers. Only set this to 'true' for domains that can't access the internet. This value is available in iOS 14 and later.
         */
        AssociatedDomainsEnableDirectDownloads?: boolean;
        /**
         * If 'false', this app isn't removable while it's a managed app. This value is available in iOS 14 and later.
         */
        Removable?: boolean;
        /**
         * Enabling this setting will require Tap to Pay on iPhone users to use Face ID or a passcode to unlock their device after every transaction that requires a customer’s card PIN. Disabling this setting will allow users to configure this setting on their device based on personal preference.
         */
        TapToPayScreenLock?: boolean;
        /**
         * Either data network name (DNN) or traffic category can be set as the enterprise slice identifier. For DNN, the value must be encoded as "DNN:name”, where "name" is the carrier provided DNN name. For app category, the value must be encoded as "AppCategory:category", where "category" is a carrier provided string like "Enterprise1".
         */
        CellularSliceUUID?: string;
      };
    }[];
  };
}
