/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleGamed {
  /**
   * If 'true', enables Game Center.
   */
  GKFeatureGameCenterAllowed?: boolean;
  /**
   * If 'true', allows account modifications.
   */
  GKFeatureAccountModificationAllowed?: boolean;
  /**
   * If 'true', allows adding Game Center friends.
   */
  GKFeatureAddingGameCenterFriendsAllowed?: boolean;
  /**
   * If 'true', allows multiplayer gaming.
   */
  GKFeatureMultiplayerGamingAllowed?: boolean;
}
