/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleDesktop {
  /**
   * If 'true', locks the desktop picture. Replaced with allowWallpaperModification in macOS 10.13.
   */
  locked?: boolean;
  /**
   * The path to the desktop picture. If set, this picture is always locked.
   */
  "override-picture-path"?: string;
}
