/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComApplePreferenceUsers {
  /**
   * If 'true', disables the iCloud password for local accounts.
   */
  DisableUsingiCloudPassword?: boolean;
}
