/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define settings for configuration access to CalDAV servers.
 */
export interface ComAppleCaldavAccount {
  /**
   * The description of the account.
   */
  CalDAVAccountDescription?: string;
  /**
   * The server's address.
   */
  CalDAVHostName: string;
  /**
   * The user name for logins.
   * If this profile part of a non-interactive install, this field is required.
   */
  CalDAVUsername?: string;
  /**
   * The user's password. This is only used with encrypted profiles.
   */
  CalDAVPassword?: string;
  /**
   * The base URL to the user's calendar.
   */
  CalDAVPrincipalURL?: string;
  /**
   * If 'true', enables SSL.
   */
  CalDAVUseSSL?: boolean;
  /**
   * The server's port.
   */
  CalDAVPort?: number;
  /**
   * The VPNUUID of the per-app VPN the account uses for network communication.
   * Available in iOS 14 and later.
   */
  VPNUUID?: string;
}
