/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to configure Google accounts. The user will be prompted to sign in afterward.
 */
export interface ComAppleGoogleOauth {
  /**
   * A user-visible description of the Google account, shown in the Mail and Settings apps.
   */
  AccountDescription?: string;
  /**
   * The user's full name for the Google account. This name appears in sent messages.
   */
  AccountName?: string;
  /**
   * The full Google email address for the account.
   */
  EmailAddress: string;
  /**
   * The communication service handler rules for this account.
   */
  CommunicationServiceRules?: {
    /**
     * A dictionary defining which app to use for audio calls made from this account.
     */
    DefaultServiceHandlers?: {
      /**
       * A string containing the bundle identifier for the default application that handles audio calls made to contacts from this account.
       */
      AudioCall?: string;
    };
  };
  /**
   * The VPNUUID of the per-app VPN the account uses for network communication.
   * Available in iOS 14 and later.
   */
  VPNUUID?: string;
}
