/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleSyspolicyKernelExtensionPolicy {
  /**
   * If 'true', nonadministrative users can approve additional kernel extensions in the Security & Privacy preferences.
   * Available in macOS 11 and later.
   */
  AllowNonAdminUserApprovals?: boolean;
  /**
   * If 'true', users can approve additional kernel extensions that configuration profiles don't explicitly allow.
   */
  AllowUserOverrides?: boolean;
  /**
   * The array of team identifiers that define which validly signed kernel extensions can load.
   */
  AllowedTeamIdentifiers?: string[];
  /**
   * The dictionary that represents a set of kernel extensions that the system always allows to load on the computer. The dictionary maps team identifiers (keys) to arrays of bundle identifiers.
   */
  AllowedKernelExtensions?: {
    /**
     * The kernel extension data.
     */
    ANY?: string[];
  };
}
