/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleLoginitemsManaged {
  /**
   * An array of login item dictionaries.
   */
  "AutoLaunchedApplicationDictionary-managed": {
    /**
     * The URL or path string to the item's location.
     */
    Path: string;
    /**
     * If 'true', hide this item in the Users & Groups login items list.
     */
    Hide?: boolean;
  }[];
}
