/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleEwsAccount {
  /**
   * The full email address for the account. If the email address string isn't present in the payload, the device prompts for it during profile installation.
   */
  EmailAddress?: string;
  /**
   * The Exchange server host name or IP address.
   * If using OAuth, the host name is ignored..
   */
  Host?: string;
  /**
   * If 'true', enables SSL.
   */
  SSL?: boolean;
  /**
   * If 'true', enables OAuth for authentication. If OAuth is enabled, don't specify a password.
   * Available in macOS 10.14 and later
   */
  OAuth?: boolean;
  /**
   * The URL to load into a web view for authentication via OAuth when autodiscovery isn't used. This setting requires a 'Host' value.
   */
  OAuthSignInURL?: string;
  /**
   * The user name for this Exchange account. This string is required for noninteractive (for example, MDM) installation. If it's missing, the device prompts for it during interactive profile installation.
   */
  UserName?: string;
  /**
   * The password of the account. Use only with encrypted profiles.
   */
  Password?: string;
  /**
   * The UUID of of the certificate payload within the same profile to use for the identity credential. Supported on macOS 10.12 or later.
   */
  PayloadCertificateUUID?: string;
  /**
   * The UUID of of the certificate payload within the same profile to use for the identity credential. Supported on macOS 10.11 or later. On macOS 10.12 or later use the PayloadCertificateUUID.
   */
  AuthenticationCertificateUUID?: string;
  /**
   * If 'true', enables Mail Drop.
   */
  allowMailDrop?: boolean;
  /**
   * The server path.
   */
  Path?: string;
  /**
   * The server port number.
   */
  Port?: number;
  /**
   * The external server address.
   */
  ExternalHost?: string;
  /**
   * If 'true', enables SSL for connections to the external server.
   */
  ExternalSSL?: boolean;
  /**
   * The external server path.
   */
  ExternalPath?: string;
  /**
   * The external server port number.
   */
  ExternalPort?: number;
}
