/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleAsam {
  /**
   * An array of dictionaries that specifies the apps that can be granted access to the Accessibility APIs.
   */
  AllowedApplications: {
    /**
     * The unique bundle identifier. If two dictionaries contain the same 'BundleIdentifier' value but a different 'TeamIdentifier' value, this will be considered an error and the profile won't be installed.
     */
    BundleIdentifier: string;
    /**
     * The developer's team identifier, used when the app was signed.
     */
    TeamIdentifier: string;
  }[];
}
