/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleEducation {
  /**
   * The organization's UUID identifier. This identifier can be any valid UUID. All teacher and student devices that need to communicate with one another must have the same organization UUID, particularly if they originated from different Device Enrollment Programs.
   */
  OrganizationUUID: string;
  /**
   * The organization's display name. This name is shown in the iOS login screen.
   */
  OrganizationName: string;
  /**
   * The UUID of an identity certificate payload within the same profile to use for performing client authentication with other devices. This property supports PKCS12 certificates.
   * This key is required to configure Classroom. It does not impact the configuration of the Shared iPad login screen.
   */
  PayloadCertificateUUID?: string;
  /**
   * The array of UUIDs referring to certificate payloads within the same profile that are used to authorize leader peer certificate identities. This array must contain all certificates needed to validate the entire chain of trust. Leader certificates must have the common name prefix leader (case insensitive).
   * Note: This property doesn't support identity payloads or PKCS12 certificates.
   * This key is required when configuring a student device for Classroom, and is ignored when configuring an instructor device. It does not impact the configuration of the Shared iPad login screen.
   */
  LeaderPayloadCertificateAnchorUUID?: string[];
  /**
   * The array of UUIDs referring to certificate payloads within the same profile that are used to authorize group member peer certificate identities. This array must contain all certificates needed to validate the entire chain of trust. Member certificates must have the common name prefix member (case insensitive).
   * Note: This property doesn't support identity payloads or PKCS12 certificates.
   * This key is required when configuring an instructor device for Classroom, and is ignored when configuring a student device. It does not impact the configuration of the Shared iPad login screen.
   */
  MemberPayloadCertificateAnchorUUID?: string[];
  /**
   * The UUID of an identity certificate payload within the same profile that is used to perform client authentication when fetching additional resources, such as student images. If not specified, the MDM client identity is used.
   * If present, this key is used to configure both Classroom and the Shared iPad login screen.
   */
  ResourcePayloadCertificateUUID?: string;
  /**
   * The unique string that identifies the user of this device within the organization.
   * If this payload is intended to configure the Shared iPad login screen, this value must not be set.
   */
  UserIdentifier: string;
  /**
   * For shared iPad profiles: The array of dictionaries that defines which departments  are shown in the Shared iPad login screen.
   * If present, this key is used to configure both Classroom and the Shared iPad login screen.
   */
  Departments?: {
    /**
     * The display name of the department.
     */
    Name: string;
    /**
     * The group beacon identifiers that are members of this department.
     */
    GroupBeaconIDs: string[];
  }[];
  /**
   * For shared iPad profiles: The array of dictionaries that defines which groups the user can select in the login window.
   *
   * For leader/teacher profiles: The array of dictionaries that defines the groups that the user can control.
   *
   * For member/student profiles: The array of dictionaries that defines the groups where the user is a member.
   */
  Groups: {
    /**
     * The group's unique beacon ID.
     */
    BeaconID: number;
    /**
     * The display name of the group.
     */
    Name: string;
    /**
     * The description of the group.
     */
    Description?: string;
    /**
     * Deprecated in iOS 9.3.1 and later. The URL of an image for the group.
     */
    ImageURL?: string;
    /**
     * The source that provided this group; for example,  iTunesU, SIS, or MDM.
     */
    ConfigurationSource?: string;
    /**
     * The user identifiers that are leaders of this group.
     */
    LeaderIdentifiers?: string[];
    /**
     * The entries in the Users array that are members of the group.
     */
    MemberIdentifiers: string[];
    /**
     * The identifiers that refer to entries in the DeviceGroups array to which the instructor can assign users from this class.
     * The presence/value of this key does not impact the configuration of the Shared iPad login screen.
     */
    DeviceGroupIdentifiers?: string[];
  }[];
  /**
   * For shared iPad profiles: The array of dictionaries that define the users that are shown in the iOS login window.
   *
   * For leader/teacher profiles: The array of dictionaries that define users that are members of the teacher's groups.
   *
   * For member/student profiles: The array of dictionaries that must contain the definition of the user specified in the 'UserIdentifier' key. With one-to-one member devices, this key should include only the device user and the teacher but not other class members.
   */
  Users: {
    /**
     * The unique identifier for a user in the organization.
     */
    Identifier: string;
    /**
     * The name of the user.
     */
    Name: string;
    /**
     * The given name of the user.
     */
    GivenName?: string;
    /**
     * The family name of the user.
     */
    FamilyName?: string;
    /**
     * The user's phonetic given name. This name is used to sort users in the Classroom app and the Shared iPad Login Screen.
     */
    PhoneticGivenName?: string;
    /**
     * The user's phonetic family name. This name is used to sort users in the Classroom app and the shared iPad login screen.
     */
    PhoneticFamilyName?: string;
    /**
     * A string containing a URL pointing to an image of the user. This image will be displayed in the iOS login screen and in the Classroom app. The recommended resolution is 256 x 256 pixels (512 x 512 pixels on a 2x device). The recommended formats are JPEG, PNG, and TIFF.
     * The 'ResourcePayloadCertificateUUID' identity certificate or the MDM client identity will be used to perform authentication when fetching the image.
     */
    ImageURL?: string;
    /**
     * Deprecated in iOS 9.3.1 and later. The URL pointing to an image of the user. The 'ResourcePayloadCertificateUUID' identity certificate or the MDM client identity will be used to perform authentication when fetching the specified resource.
     */
    FullScreenImageURL?: string;
    /**
     * The managed Apple ID for this user.
     * This key is not required to configure Classroom, but it is used by Classroom if it is present.
     * This key is required when configuring the Shared iPad login screen.
     */
    AppleID?: string;
    /**
     * The type of passcode UI to show when the user is at the login window.
     */
    PasscodeType?: "complex" | "four" | "six";
  }[];
  /**
   * For leader/teacher profiles: The array of dictionaries that defines which device groups the leader can assign devices to. This key is not included in member payloads.
   */
  DeviceGroups?: {
    /**
     * The unique identifier for the device group in the organization.
     */
    Identifier: string;
    /**
     * The name of the device group, which must be unique in the organization.
     */
    Name: string;
    /**
     * The serial numbers of the devices in the group.
     */
    SerialNumbers: string[];
  }[];
  /**
   * If 'true', allows students enrolled in managed classes to modify their teacher's permissions for screen observation on their device.
   */
  ScreenObservationPermissionModificationAllowed?: boolean;
}
