/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define Domains settings.
 */
export interface ComAppleDomains {
  /**
   * An array of domains. The system considers email addresses that lack a suffix matching any of these strings out of domain and marked in Mail.
   * Available in iOS 8 and later and macOS 10.10 and later.
   */
  EmailDomains?: string[];
  /**
   * An array of domains. The system considers URLs matching the patterns listed in this property managed.
   * Available in iOS 9.3 and later.
   */
  WebDomains?: string[];
  /**
   * An array of domains. Users can only save passwords in Safari from URLs matching the patterns listed here. This property doesn't disable the autofill feature itself.
   * Supervised devices or Shared iPads need this property to enable saving passwords in Safari.
   * Available in iOS 9.3 and later.
   */
  SafariPasswordAutoFillDomains?: string[];
  /**
   * An array of up to 10 strings. URLs matching the patterns listed here have relaxed enforcement of cross-site tracking prevention.
   * Available in iOS 16.2 and later and macOS 13.1 and later.
   */
  CrossSiteTrackingPreventionRelaxedDomains?: string[];
}
