/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleHomescreenlayout {
  /**
   * An array of dictionaries, each of which must conform to the icon dictionary format. If this key isn't present, the user's dock is empty.
   */
  Dock?: {
    /**
     * The type of the dock item.
     */
    Type: "App" | "Folder" | "WebClip";
    /**
     * The human-readable string shown to the user. This setting is valid only if the type is 'Folder'.
     */
    DisplayName?: string;
    /**
     * The bundle identifier of the app. This setting is required if the type is 'Application'.
     */
    BundleID?: string;
    /**
     * An array of arrays of dictionaries, each conforming to the icon dictionary format. This setting is valid only if the type is 'Folder'.
     */
    Pages?: unknown[][];
    /**
     * The URL of the existing web clip for this item. This setting is required if 'type' is 'WebClip'. If more than one web clip exists with the same URL, the behavior is undefined.
     * Specifying a web clip in this payload doesn't create the web clip. Use the WebClip payload to create a web clip.
     */
    URL?: string;
  }[];
  /**
   * An array of arrays of dictionaries, each of which must conform to the icon dictionary format.
   */
  Pages: {
    /**
     * The type of the dock item.
     */
    Type: "App" | "Folder" | "WebClip";
    /**
     * The human-readable string shown to the user. This setting is valid only if the type is 'Folder'.
     */
    DisplayName?: string;
    /**
     * The bundle identifier of the app. This setting is required if the type is 'Application'.
     */
    BundleID?: string;
    /**
     * An array of arrays of dictionaries, each conforming to the icon dictionary format. This setting is valid only if the type is 'Folder'.
     */
    Pages?: unknown[];
    /**
     * The URL of the existing web clip for this item. This setting is required if 'type' is 'WebClip'. If more than one web clip exists with the same URL, the behavior is undefined.
     * Specifying a web clip in this payload doesn't create the web clip. Use the WebClip payload to create a web clip.
     */
    URL?: string;
  }[][];
}
