/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface ComAppleNSExtension {
  /**
   * An array of identifiers for extensions that are allowed to run on the system.
   */
  AllowedExtensions?: string[];
  /**
   * An array of identifiers for extensions that aren't allowed to run on the system.
   */
  DeniedExtensions?: string[];
  /**
   * An array of extension points for extensions that aren't allowed to run on the system.
   */
  DeniedExtensionPoints?: string[];
}
