/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Software Update Managed Settings
 */
export interface ComAppleSoftwareUpdate {
  /**
   * The URL of the software update catalog. This property is not supported in macOS 11 and later.
   */
  CatalogURL?: string;
  /**
   * If 'true', prerelease software can be installed on this computer.
   */
  AllowPreReleaseInstallation?: boolean;
  /**
   * If 'true', restrict app installations to admin users. This key has the same function as the  'restrict-store-require-admin-to-install' key in the 'com.apple.appstore' payload.
   */
  "restrict-software-update-require-admin-to-install"?: boolean;
  /**
   * If 'false', restricts the 'Install macOS Updates' option and prevents the user from changing the option.
   */
  AutomaticallyInstallMacOSUpdates?: boolean;
  /**
   * If 'false', deselects the 'Install app updates from the App Store' option and prevents the user from changing the option.
   */
  AutomaticallyInstallAppUpdates?: boolean;
  /**
   * If 'false', deselects the 'Check for updates' option and prevents the user from changing the option.
   */
  AutomaticCheckEnabled?: boolean;
  /**
   * If 'false', deselects the 'Download new updates when available from the App Store' option and prevents the user from changing the option.
   */
  AutomaticDownload?: boolean;
  /**
   * If 'false', disables the automatic installation of critical updates and prevents the user from changing the 'Install system data files and security updates' option.
   */
  CriticalUpdateInstall?: boolean;
  /**
   * If 'false', restricts the automatic installation of configuration data.
   */
  ConfigDataInstall?: boolean;
}
