/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this section to define web clips
 */
export interface ComAppleWebClipManaged {
  /**
   * If 'true', prevents SpringBoard from adding 'shine' to the icon.
   */
  Precomposed?: boolean;
  /**
   * If 'true', launches the web clip as a full-screen web app.
   */
  FullScreen?: boolean;
  /**
   * The URL that the web clip should open when clicked.
   */
  URL: string;
  /**
   * The PNG icon to be shown on the Home screen.
   * For best results, provide a square image that's no larger than 400 x 400 pixels and less than 1 MB when uncompressed. The graphics file is automatically scaled and cropped to fit, if necessary, and converted to PNG format. Web clip icons are 144 x 144 pixels for iPad devices with a Retina display, and 114 x 114 pixels for iPhone devices. To prevent the device from adding a shine to the image, set 'Precomposed' to 'true'.
   * If this property isn't specified, a white square is shown.
   */
  Icon?: string;
  /**
   * If 'true', enables removing the web clip.
   */
  IsRemovable?: boolean;
  /**
   * The name of the web clip as displayed on the Home screen.
   */
  Label: string;
  /**
   * If 'true', a full screen web clip can navigate to an external web site without showing Safari UI. Otherwise, Safari UI appears when navigating away from the web clip's URL.
   * This key has no effect when 'FullScreen' is 'false'.
   * Available in iOS 14 and later.
   */
  IgnoreManifestScope?: boolean;
  /**
   * The application bundle identifier that specifies the application which opens the URL. To use this property, the profile must be installed through an MDM.
   * Available in iOS 14 and later.
   */
  TargetApplicationBundleIdentifier?: string;
}
