/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to ask for the device's location if it is in MDM lost mode.
 */
export interface DeviceLocationCommand {
  PayloadKeys?: {};
  ResponseKeys?: {
    /**
     * The latitude of the device's location.
     */
    Latitude: number;
    /**
     * The longitude of the device's location.
     */
    Longitude: number;
    /**
     * The radius of uncertainty for the location in meters, which is a negative value if the horizontal accuracy is unknown.
     */
    HorizontalAccuracy: number;
    /**
     * The accuracy of the altitude value in meters, which is a negative value if the vertical accuracy is unknown.
     */
    VerticalAccuracy: number;
    /**
     * The altitude of the device's location, which is a negative value if the altitude is unknown.
     */
    Altitude: number;
    /**
     * The speed of the device in meters per second, which is a negative value if the speed is unknown.
     */
    Speed: number;
    /**
     * The direction the device is traveling, which is a negative value if the course is unknown.
     */
    Course: number;
    /**
     * The RFC 3339 timestamp of when the server determined the location of the device.
     */
    Timestamp: string;
  };
}
