/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to determine what restrictions are being enforced on the device, and the total sum of all restrictions. This command requires the Restrictions Query access right.
 */
export interface DeviceRestrictionsCommand {
  PayloadKeys?: {
    /**
     * If 'true', the device reports restrictions from each profile. This value is available in iOS 4 and later, and tvOS 6.1 and later.
     */
    ProfileRestrictions?: boolean;
  };
  ResponseKeys?: {
    /**
     * A dictionary that contains the global restrictions in effect. This value is available in iOS 4 and later, and tvOS 6.1 and later.
     */
    GlobalRestrictions: {
      /**
       * A dictionary of Boolean restrictions.
       */
      restrictedBool?: {
        /**
         * The Boolean restriction parameters.
         */
        "ANY restriction name"?: {
          /**
           * The value of the restriction.
           */
          value: boolean;
        };
      };
      /**
       * A dictionary of numeric restrictions.
       */
      restrictedValue?: {
        /**
         * The numeric restriction parameters.
         */
        "ANY restriction name"?: {
          /**
           * The value of the restriction.
           */
          value: number;
        };
      };
      /**
       * A dictionary of intersected restrictions. Intersected restrictions indicate that new restrictions can only reduce the number of strings in the set.
       */
      intersection?: {
        /**
         * The intersected restriction parameters.
         */
        "ANY restriction name"?: {
          /**
           * The values of the restriction.
           */
          values: string[];
        };
      };
      /**
       * A dictionary of unioned restrictions. Unioned restrictions indicate that new restrictions can add to the set.
       */
      union?: {
        /**
         * The unioned restriction parameters.
         */
        "ANY restriction name"?: {
          /**
           * The values of the restriction.
           */
          values: string[];
        };
      };
    };
    /**
     * A dictionary that contains dictionaries of restrictions from each profile. This value is only available when 'ProfileRestrictions' is 'true' in the command. The keys are the identifiers of the profiles. This value is available in iOS 4 and later, and tvOS 6.1 and later.
     */
    ProfileRestrictions: {
      /**
       * The profile identifiers.
       */
      "ANY profile identifier"?: {
        /**
         * A dictionary of Boolean restrictions.
         */
        restrictedBool?: {
          /**
           * The Boolean restriction parameters.
           */
          "ANY restriction name"?: {
            /**
             * The value of the restriction.
             */
            value: boolean;
          };
        };
        /**
         * A dictionary of numeric restrictions.
         */
        restrictedValue?: {
          /**
           * The numeric restriction parameters.
           */
          "ANY restriction name"?: {
            /**
             * The value of the restriction.
             */
            value: number;
          };
        };
        /**
         * A dictionary of intersected restrictions. Intersected restrictions indicate that new restrictions can only reduce the number of strings in the set.
         */
        intersection?: {
          /**
           * The intersected restriction parameters.
           */
          "ANY restriction name"?: {
            /**
             * The values of the restriction.
             */
            values: string[];
          };
        };
        /**
         * A dictionary of unioned restrictions. Unioned restrictions indicate that new restrictions can add to the set.
         */
        union?: {
          /**
           * The unioned restriction parameters.
           */
          "ANY restriction name"?: {
            /**
             * The values of the restriction.
             */
            values: string[];
          };
        };
      };
    };
  };
}
