/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to put the device in MDM lost mode, with a message, phone number, and footnote text. A message or phone number must be provided.
 */
export interface EnableMDMLostModeCommand {
  /**
   * If present, display this text on the Lock screen. You must provide this value if you don't provide a value for 'PhoneNumber'.
   */
  Message?: string;
  /**
   * If present, display this phone number on the Lock screen. You must provide this value if you don't provide a value for 'Message'.
   */
  PhoneNumber?: string;
  /**
   * If present, display this text in place of Slide to Unlock.
   */
  Footnote?: string;
}
