/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

export interface GlobalPreferences {
  /**
   * If 'false', disables fast user switching.
   */
  MultipleSessionEnabled?: boolean;
  /**
   * The 'autologout' delay, in seconds. A value of '0' means 'autologout' is off. In some cases, this delay may be restricted to values between 5 minutes and 24 hours.
   */
  "com.apple.autologout.AutoLogOutDelay"?: number;
}
