/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows a server to invite a user to join a program.
 */
export interface InviteToProgramCommand {
  PayloadKeys?: {
    /**
     * The program's identifier, which can only be 'com.apple.cloudvpp'.
     */
    ProgramID?: "com.apple.cloudvpp";
    /**
     * The Volume Purchase Program (VPP) invitation URL.
     */
    InvitationURL?: string;
  };
  ResponseKeys?: {
    /**
     * The result of the command.
     */
    InvitationResult: "Acknowledged" | "InvalidProgramID" | "InvalidInvitationURL";
  };
}
