/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Queries the device for LOM setup information such as IP addresses, protocol version, etc.
 */
export interface LOMSetupRequestCommand {
  PayloadKeys?: {};
  ResponseKeys?: {
    /**
     * An array that contains the IPv6 addresses for primary LOM-compatible Ethernet interfaces for the device.
     */
    PrimaryIPv6AddressList: string[];
    /**
     * An array that contains the IPv6 addresses for secondary LOM-compatible Ethernet interfaces for the device.
     */
    SecondaryIPv6AddressList: string[];
    /**
     * The LOM protocol version that the device supports.
     */
    LOMProtocolVersion: number;
  };
}
