/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to query for installed 3rd party applications.
 */
export interface ManagedMediaListCommand {
  PayloadKeys?: {};
  ResponseKeys?: {
    /**
     * An array of dictionaries that describes managed books.
     */
    Books: {
      /**
       * The book's iTunes Store identifier.
       */
      iTunesStoreID: number;
      /**
       * The installation state of this book, which is one of the following values:
       * * 'Queued'
       * * 'PromptingForLogin'
       * * 'Updating'
       * * 'Installing'
       * * 'Managed'
       * * 'ManagedButUninstalled'
       * * 'Installed'
       * * 'Uninstalled'
       * * 'Failed'
       * * 'Unknown'
       * The 'Failed' and 'Unknown' states are transient and the device only reports them once. Books from the Book Store report their state as 'Installed' instead of 'Managed'.
       */
      State?: string;
      /**
       * The book's persistent identifier in reverse-DNS form; for example, 'com.acme.manuals.training'.
       */
      PersistentID?: string;
      /**
       * The kind of the media, which is one of the following values:
       * * 'pdf': A PDF file
       * * 'epub': An EPUB file in 'gzip' format
       * * 'ibooks': An iBooks Author file in 'gzip' format
       * * The file extension in the URL
       * This value is available in iOS 8 and later.
       */
      Kind?: string;
      /**
       * The book's version number.
       */
      Version?: string;
      /**
       * The name of the book's author.
       */
      Author?: string;
      /**
       * The book's title.
       */
      Title?: string;
    }[];
  };
}
