/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the MDM server to query for the profiles installed on the device. This command requires the Inspect Profile Manifest right. It's supported on the user channel.
 */
export interface ProfileListCommand {
  PayloadKeys?: {
    /**
     * If 'true', only include profiles that MDM has installed. For user enrollments, the device ignores this key and always limits the results to managed profiles. This value is available in iOS 13 and later, macOS 10.5 and later, and tvOS 13 and later.
     */
    ManagedOnly?: boolean;
  };
  ResponseKeys?: {
    /**
     * An array of dictionaries that describes each installed profile.
     */
    ProfileList: {
      /**
       * The unique identifier for the profile.
       */
      PayloadUUID: string;
      /**
       * The reverse-DNS-style identifier of the profile; for example, 'com.example.myprofile'.
       */
      PayloadIdentifier: string;
      /**
       * The version of the configuration profile as a whole, not of the individual profiles within it. The value should be '1'.
       */
      PayloadVersion?: number;
      /**
       * The human-readable name of the profile.
       */
      PayloadDisplayName?: string;
      /**
       * The human-readable name of the organization that provided the profile.
       */
      PayloadOrganization?: string;
      /**
       * The description of the profile.
       */
      PayloadDescription?: string;
      /**
       * If 'true', the user can't delete the profile unless it has a removal password and the user provides it. The framework ignores this field on unsupervised devices.
       */
      PayloadRemovalDisallowed?: boolean;
      /**
       * If 'true', the profile has a passcode for removal.
       */
      HasRemovalPasscode?: boolean;
      /**
       * If 'true', it's an encrypted profile.
       */
      IsEncrypted?: boolean;
      /**
       * An array that contains the certificate for signing the profile, followed by any intermediate certificates, in DER-encoded X.509 format.
       */
      SignerCertificates?: string[];
      /**
       * If 'true', the current MDM service installed the profile. MDM doesn't return this value for supervised devices, and can remove or replace all profiles on supervised devices.
       */
      IsManaged?: boolean;
      /**
       * An array of payload content items. This value isn't present if 'IsEncrypted' is 'true'.
       */
      PayloadContent?: {
        /**
         * The payload type, which each payload domain’s reference page specifies.
         */
        PayloadType: string;
        /**
         * The version of the configuration payload. The value should be '1'.
         */
        PayloadVersion: number;
        /**
         * The reverse-DNS-style identifier of the payload; for example, 'com.example.myprofile.payload1'.
         */
        PayloadIdentifier: string;
        /**
         * The unique identifier for the profile.
         */
        PayloadUUID: string;
        /**
         * The human-readable name of the payload.
         */
        PayloadDisplayName?: string;
        /**
         * The description of the payload.
         */
        PayloadDescription?: string;
        /**
         * The human-readable name of the organization that provided the payload.
         */
        PayloadOrganization?: string;
      }[];
    }[];
  };
}
