/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to retrieve the list of installed provisioning profiles on the device. This command requires the Inspect Provisioning Profiles right. On macOS, this command is for iOS and iPadOS style provisioning profiles only.
 */
export interface ProvisioningProfileListCommand {
  PayloadKeys?: {
    /**
     * If 'true', only include profiles that MDM has installed. For user enrollments, the device ignores this key and always limits the results to managed profiles. This value is available in iOS 13 and later, and tvOS 13 and later.
     */
    ManagedOnly?: boolean;
  };
  ResponseKeys?: {
    /**
     * An array of dictionaries that describes each installed profile.
     */
    ProvisioningProfileList: {
      /**
       * The display name of the provisioning profile.
       */
      Name: string;
      /**
       * The unique identifier for the provisioning profile.
       */
      UUID: string;
      /**
       * The expiry date of the provisioning profile.
       */
      ExpiryDate?: string;
    }[];
  };
}
