/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command allows the server to remove a profile. This command requires the Profile Installation and Removal Right. It's supported in the user channel.
 */
export interface RemoveProfileCommand {
  /**
   * The identifier of the profile to remove.
   */
  Identifier: string;
}
