/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This command prompts the user to share their screen using AirPlay mirroring.
 */
export interface RequestMirroringCommand {
  PayloadKeys?: {
    /**
     * The name of the AirPlay Mirroring destination.
     */
    DestinationName?: string;
    /**
     * The hardware address of the AirPlay Mirroring destination that identifies the device, in the format 'xx:xx:xx:xx:xx'. This value isn't case-sensitive.
     */
    DestinationDeviceID?: string;
    /**
     * The number of seconds, from '10' to '300', for the device to spend searching for the destination. The default value is '30'.
     */
    ScanTime?: number;
    /**
     * The screen-sharing password that the device uses when connecting to the destination.
     */
    Password?: string;
  };
  ResponseKeys?: {
    /**
     * The result of the request. One of these values:
     * * 'Prompting': The user is receiving a prompt to share their screen.
     * * 'DestinationNotFound': The device is unable to reach the destination.
     * * 'Cancelled': The user canceled the request.
     * * 'Unknown': An unknown error occurred.
     */
    MirroringResult?: string;
  };
}
