/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Use this configuration to install an identity on the device.
 */
export interface SecurityIdentity {
  /**
   * Specifies the identifier of an asset declaration that contains the identity to install.
   */
  CredentialAssetReference: string;
  /**
   * If 'true', apps can access the private key.
   */
  AllowAllAppsAccess?: boolean;
  /**
   * If 'true', the private key is extractable in the keychain.
   */
  KeyIsExtractable?: boolean;
}
