/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Changes or clears the firmware password for the device.
 */
export interface SetFirmwarePasswordCommand {
  PayloadKeys?: {
    /**
     * The current password, which you must set if the device has a firmware password.
     */
    CurrentPassword?: string;
    /**
     * The new firmware password. Set to an empty string to clear the password. The characters in this value must consist of low-ASCII, printable characters ('0x20' through '0x7E') to ensure that all characters are enterable on the EFI login screen.
     */
    NewPassword?: string;
    /**
     * If 'true', enable ROMs.
     */
    AllowOroms?: boolean;
  };
  ResponseKeys?: {
    /**
     * Command result.
     */
    SetFirmwarePassword: {
      /**
       * If 'true', the password change succeeded.
       */
      PasswordChanged: boolean;
    };
  };
}
