/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * A software update enforcement policy for a specific OS release
 */
export interface SoftwareUpdateEnforcementSpecific {
  /**
   * The target OS version to update the device to by the appropriate time. This is the OS version number, for example, '16.1'. It may also include a supplemental version identifier, for example, '16.1.1'.
   */
  TargetOSVersion: string;
  /**
   * The target build version to update the device to by the appropriate time, for example, '20A242'. The system uses the build version for testing during seeding periods. The build version can include a supplemental version identifier, for example, '20A242a'. If the build version isn't consistent with the target OS version specified in the 'TargetOSVersion' key, the target OS version takes precedence.
   */
  TargetBuildVersion?: string;
  /**
   * The local date time value that specifies when to force install the software update. Use the format 'yyyy-mm-ddThh:mm:ss', which is derived from RFC3339 but doesn't include a time zone offset. If the user doesn't trigger the software update before this time, the device force installs it.
   */
  TargetLocalDateTime: string;
  /**
   * The URL of a web page that shows details that the organization provides about the enforced update.
   */
  DetailsURL?: string;
}
