/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * This commands allows the server to force validation of the free developer and universal provisioning profiles associated with an enterprise app.
 */
export interface ValidateApplicationsCommand {
  /**
   * The bundle identifiers of the enterprise apps to include for validation of associated provisioning profiles, if you choose to provide them. Otherwise, validation occurs for the provisioning profiles for the installed managed apps.
   */
  Identifiers?: string[];
}
