/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Verifies the device's recovery lock password. (AppleSilicon devices only)
 */
export interface VerifyRecoveryLockCommand {
  PayloadKeys?: {
    /**
     * The password to verify.
     */
    Password?: string;
  };
  ResponseKeys?: {
    /**
     * If 'true', the device verified the password.
     */
    PasswordVerified: boolean;
  };
}
