/* eslint-disable */
/**
 * This file was automatically generated by mdm-docs-parser.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run mdm-docs-parser:generate to regenerate this file.
 */

/**
 * Verifies the device's firmware password.
 */
export interface VerifyFirmwarePasswordCommand {
  PayloadKeys?: {
    /**
     * The password to verify.
     */
    Password?: string;
  };
  ResponseKeys?: {
    /**
     * Command result.
     */
    VerifyFirmwarePassword: {
      /**
       * If 'true', the provided password matched the firmware password set for the device.
       */
      PasswordVerified: boolean;
    };
  };
}
